namespace FormSetup
{
  partial class TfrmSetup
    {
        public System.Windows.Forms.TabControl PageControl;
        public System.Windows.Forms.TabPage tabServer;
        public System.Windows.Forms.Panel Panel1;
        public System.Windows.Forms.Label Label12;
        public System.Windows.Forms.Label Label3;
        public System.Windows.Forms.Label Label1;
        public System.Windows.Forms.Label Label13;
        public System.Windows.Forms.Label Label14;
        public System.Windows.Forms.Label Label15;
        public System.Windows.Forms.Label Label16;
        public System.Windows.Forms.Label Label17;
        public System.Windows.Forms.TextBox tbHost;
        public System.Windows.Forms.TextBox tbPort;
        public System.Windows.Forms.TextBox tbSectors;
        public System.Windows.Forms.TextBox tbLoginScript;
        public System.Windows.Forms.CheckBox cbUseLogin;
        public System.Windows.Forms.TextBox tbLoginName;
        public System.Windows.Forms.TextBox tbPassword;
        public System.Windows.Forms.TextBox tbGame;
        public System.Windows.Forms.TextBox tbDescription;
        public System.Windows.Forms.Button btnSave;
        public System.Windows.Forms.Button btnCancel;
        public System.Windows.Forms.ComboBox cbGames;
        public System.Windows.Forms.Button btnAdd;
        public System.Windows.Forms.Button btnDelete;
        public System.Windows.Forms.Button btnEdit;
        public System.Windows.Forms.TabPage tabProgram;
        public System.Windows.Forms.Label Label2;
        public System.Windows.Forms.Label Label11;
        public System.Windows.Forms.Label Label10;
        public System.Windows.Forms.CheckBox cbAcceptExternal;
        public System.Windows.Forms.CheckBox cbBroadcast;
        public System.Windows.Forms.TextBox tbListenPort;
        public System.Windows.Forms.TextBox tbMenuKey;
        public System.Windows.Forms.CheckBox cbReconnect;
        public System.Windows.Forms.CheckBox cbCache;
        public System.Windows.Forms.TextBox tbBubbleSize;
        public System.Windows.Forms.CheckBox cbLocalEcho;
        public System.Windows.Forms.TabPage tabLogging;
        public System.Windows.Forms.Label Label9;
        public System.Windows.Forms.Label Label20;
        public System.Windows.Forms.CheckBox cbLog;
        public System.Windows.Forms.CheckBox cbLogANSI;
        public System.Windows.Forms.CheckBox cbLogBinary;
        public System.Windows.Forms.CheckBox cbNotifyLogDelay;
        public System.Windows.Forms.TextBox tbShortenDelay;
        public System.Windows.Forms.TabPage tabAutoRun;
        public System.Windows.Forms.ListBox lbAutoRun;
        public System.Windows.Forms.TextBox memHint3;
        public System.Windows.Forms.Button btnAddAutoRun;
        public System.Windows.Forms.Button btnRemoveAutoRun;
        public System.Windows.Forms.TabPage tabUser;
        public System.Windows.Forms.Label Label18;
        public System.Windows.Forms.Label Label19;
        public System.Windows.Forms.Label Label4;
        public System.Windows.Forms.Label Label5;
        public System.Windows.Forms.TextBox memHint2;
        public System.Windows.Forms.TextBox tbUser;
        public System.Windows.Forms.TextBox tbRegKey;
        public System.Windows.Forms.CheckBox cbAuthenticate;
        public System.Windows.Forms.Button btnUpgrade;
        public System.Windows.Forms.TabPage tabProxy;
        public System.Windows.Forms.Label Label6;
        public System.Windows.Forms.Label Label7;
        public System.Windows.Forms.Label Label8;
        public System.Windows.Forms.CheckBox cbUseAuthProxy;
        public System.Windows.Forms.TextBox tbProxyAddress;
        public System.Windows.Forms.TextBox tbProxyPort;
        public System.Windows.Forms.Button btnOKMain;
        public System.Windows.Forms.Button btnCancelMain;
        public System.Windows.Forms.OpenFileDialog OpenDialog;
        public System.Windows.Forms.Timer tmrReg;
        private System.ComponentModel.Container components = null;
        private System.Windows.Forms.ToolTip toolTip1 = null;

        // Clean up any resources being used.
        protected override void Dispose(bool disposing)
        {
            if(disposing)
            {
                if(components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

#region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.Resources.ResourceManager resources = new System.Resources.ResourceManager(this.GetType());
            this.components = new System.ComponentModel.Container();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.PageControl = new System.Windows.Forms.TabControl();
            this.tabServer = new System.Windows.Forms.TabPage();
            this.Panel1 = new System.Windows.Forms.Panel();
            this.Label12 = new System.Windows.Forms.Label();
            this.Label3 = new System.Windows.Forms.Label();
            this.Label1 = new System.Windows.Forms.Label();
            this.Label13 = new System.Windows.Forms.Label();
            this.Label14 = new System.Windows.Forms.Label();
            this.Label15 = new System.Windows.Forms.Label();
            this.Label16 = new System.Windows.Forms.Label();
            this.Label17 = new System.Windows.Forms.Label();
            this.tbHost = new System.Windows.Forms.TextBox();
            this.tbPort = new System.Windows.Forms.TextBox();
            this.tbSectors = new System.Windows.Forms.TextBox();
            this.tbLoginScript = new System.Windows.Forms.TextBox();
            this.cbUseLogin = new System.Windows.Forms.CheckBox();
            this.tbLoginName = new System.Windows.Forms.TextBox();
            this.tbPassword = new System.Windows.Forms.TextBox();
            this.tbGame = new System.Windows.Forms.TextBox();
            this.tbDescription = new System.Windows.Forms.TextBox();
            this.btnSave = new System.Windows.Forms.Button();
            this.btnCancel = new System.Windows.Forms.Button();
            this.cbGames = new System.Windows.Forms.ComboBox();
            this.btnAdd = new System.Windows.Forms.Button();
            this.btnDelete = new System.Windows.Forms.Button();
            this.btnEdit = new System.Windows.Forms.Button();
            this.tabProgram = new System.Windows.Forms.TabPage();
            this.Label2 = new System.Windows.Forms.Label();
            this.Label11 = new System.Windows.Forms.Label();
            this.Label10 = new System.Windows.Forms.Label();
            this.cbAcceptExternal = new System.Windows.Forms.CheckBox();
            this.cbBroadcast = new System.Windows.Forms.CheckBox();
            this.tbListenPort = new System.Windows.Forms.TextBox();
            this.tbMenuKey = new System.Windows.Forms.TextBox();
            this.cbReconnect = new System.Windows.Forms.CheckBox();
            this.cbCache = new System.Windows.Forms.CheckBox();
            this.tbBubbleSize = new System.Windows.Forms.TextBox();
            this.cbLocalEcho = new System.Windows.Forms.CheckBox();
            this.tabLogging = new System.Windows.Forms.TabPage();
            this.Label9 = new System.Windows.Forms.Label();
            this.Label20 = new System.Windows.Forms.Label();
            this.cbLog = new System.Windows.Forms.CheckBox();
            this.cbLogANSI = new System.Windows.Forms.CheckBox();
            this.cbLogBinary = new System.Windows.Forms.CheckBox();
            this.cbNotifyLogDelay = new System.Windows.Forms.CheckBox();
            this.tbShortenDelay = new System.Windows.Forms.TextBox();
            this.tabAutoRun = new System.Windows.Forms.TabPage();
            this.lbAutoRun = new System.Windows.Forms.ListBox();
            this.memHint3 = new System.Windows.Forms.TextBox();
            this.btnAddAutoRun = new System.Windows.Forms.Button();
            this.btnRemoveAutoRun = new System.Windows.Forms.Button();
            this.tabUser = new System.Windows.Forms.TabPage();
            this.Label18 = new System.Windows.Forms.Label();
            this.Label19 = new System.Windows.Forms.Label();
            this.Label4 = new System.Windows.Forms.Label();
            this.Label5 = new System.Windows.Forms.Label();
            this.memHint2 = new System.Windows.Forms.TextBox();
            this.tbUser = new System.Windows.Forms.TextBox();
            this.tbRegKey = new System.Windows.Forms.TextBox();
            this.cbAuthenticate = new System.Windows.Forms.CheckBox();
            this.btnUpgrade = new System.Windows.Forms.Button();
            this.tabProxy = new System.Windows.Forms.TabPage();
            this.Label6 = new System.Windows.Forms.Label();
            this.Label7 = new System.Windows.Forms.Label();
            this.Label8 = new System.Windows.Forms.Label();
            this.cbUseAuthProxy = new System.Windows.Forms.CheckBox();
            this.tbProxyAddress = new System.Windows.Forms.TextBox();
            this.tbProxyPort = new System.Windows.Forms.TextBox();
            this.btnOKMain = new System.Windows.Forms.Button();
            this.btnCancelMain = new System.Windows.Forms.Button();
            this.OpenDialog = new System.Windows.Forms.OpenFileDialog();
            this.tmrReg = new System.Windows.Forms.Timer();
            this.SuspendLayout();
            this.Location  = new System.Drawing.Point(263, 170);
            this.ClientSize  = new System.Drawing.Size(369, 377);
            this.Font  = new System.Drawing.Font("MS Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point ,((byte)(1)));
            this.AutoSize = true;
            this.Closed += new System.EventHandler(this.FormClose);
            this.AutoScroll = true;
            this.Name = "frmSetup";
            this.Text = "Setup";
            this.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.PageControl.Size  = new System.Drawing.Size(369, 345);
            this.PageControl.Location  = new System.Drawing.Point(0, 0);
            this.PageControl.SuspendLayout();
            this.PageControl.SelectedTab = tabServer;
            this.PageControl.TabIndex = 0;
            this.PageControl.Enabled = true;
            this.PageControl.Name = "PageControl";
            this.tabServer.Size  = new System.Drawing.Size(0, 0);
            this.tabServer.Location  = new System.Drawing.Point(0, 0);
            this.tabServer.SuspendLayout();
            this.tabServer.Text = "Server";
            this.tabServer.Enabled = true;
            this.tabServer.Name = "tabServer";
            this.Panel1.Size  = new System.Drawing.Size(313, 233);
            this.Panel1.Location  = new System.Drawing.Point(24, 80);
            this.Panel1.SuspendLayout();
            this.Panel1.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.Panel1.TabIndex = 0;
            this.Panel1.Enabled = true;
            this.Panel1.Name = "Panel1";
            this.Label12.Size  = new System.Drawing.Size(36, 13);
            this.Label12.Location  = new System.Drawing.Point(8, 73);
            this.Label12.Text = "Sectors";
            this.Label12.Enabled = true;
            this.Label12.Name = "Label12";
            this.Label3.Size  = new System.Drawing.Size(19, 13);
            this.Label3.Location  = new System.Drawing.Point(8, 51);
            this.Label3.Text = "Port";
            this.Label3.Enabled = true;
            this.Label3.Name = "Label3";
            this.Label1.Size  = new System.Drawing.Size(71, 13);
            this.Label1.Location  = new System.Drawing.Point(8, 30);
            this.Label1.Text = "Server address";
            this.Label1.Enabled = true;
            this.Label1.Name = "Label1";
            this.Label13.Size  = new System.Drawing.Size(27, 13);
            this.Label13.Location  = new System.Drawing.Point(32, 118);
            this.Label13.Text = "Script";
            this.Label13.Enabled = true;
            this.Label13.Name = "Label13";
            this.Label14.Size  = new System.Drawing.Size(57, 13);
            this.Label14.Location  = new System.Drawing.Point(32, 139);
            this.Label14.Text = "Login Name";
            this.Label14.Enabled = true;
            this.Label14.Name = "Label14";
            this.Label15.Size  = new System.Drawing.Size(46, 13);
            this.Label15.Location  = new System.Drawing.Point(32, 161);
            this.Label15.Text = "Password";
            this.Label15.Enabled = true;
            this.Label15.Name = "Label15";
            this.Label16.Size  = new System.Drawing.Size(28, 13);
            this.Label16.Location  = new System.Drawing.Point(32, 182);
            this.Label16.Text = "Game";
            this.Label16.Enabled = true;
            this.Label16.Name = "Label16";
            this.Label17.Size  = new System.Drawing.Size(28, 13);
            this.Label17.Location  = new System.Drawing.Point(8, 9);
            this.Label17.Text = "Name";
            this.Label17.Enabled = true;
            this.Label17.Name = "Label17";
            this.tbHost.Size  = new System.Drawing.Size(209, 21);
            this.tbHost.Location  = new System.Drawing.Point(96, 28);
            this.tbHost.TabIndex = 1;
            this.tbHost.Text = "<Server>";
            this.tbHost.Enabled = false;
            this.tbHost.Name = "tbHost";
            this.tbPort.Size  = new System.Drawing.Size(41, 21);
            this.tbPort.Location  = new System.Drawing.Point(96, 49);
            this.tbPort.TabIndex = 2;
            this.tbPort.Text = "23";
            this.tbPort.Enabled = false;
            this.tbPort.Name = "tbPort";
            this.tbSectors.Size  = new System.Drawing.Size(161, 21);
            this.tbSectors.Location  = new System.Drawing.Point(96, 70);
            this.tbSectors.TabIndex = 3;
            this.tbSectors.Text = "5000";
            this.tbSectors.Enabled = false;
            this.tbSectors.Name = "tbSectors";
            this.tbLoginScript.Size  = new System.Drawing.Size(161, 21);
            this.tbLoginScript.Location  = new System.Drawing.Point(96, 116);
            this.tbLoginScript.TabIndex = 5;
            this.tbLoginScript.Enabled = false;
            this.tbLoginScript.Name = "tbLoginScript";
            this.cbUseLogin.Size  = new System.Drawing.Size(185, 17);
            this.cbUseLogin.Location  = new System.Drawing.Point(8, 96);
            this.cbUseLogin.TabIndex = 4;
            this.cbUseLogin.Text = "Use login script";
            this.cbUseLogin.Enabled = false;
            this.cbUseLogin.Click += new System.EventHandler(this.cbUseLoginClick);
            this.cbUseLogin.Name = "cbUseLogin";
            this.tbLoginName.Size  = new System.Drawing.Size(121, 21);
            this.tbLoginName.Location  = new System.Drawing.Point(96, 137);
            this.tbLoginName.TabIndex = 6;
            this.tbLoginName.Enabled = false;
            this.tbLoginName.Name = "tbLoginName";
            this.tbPassword.Size  = new System.Drawing.Size(121, 21);
            this.tbPassword.Location  = new System.Drawing.Point(96, 158);
            this.tbPassword.TabIndex = 7;
            this.tbPassword.Enabled = false;
            this.tbPassword.Name = "tbPassword";
            this.tbGame.Size  = new System.Drawing.Size(25, 21);
            this.tbGame.Location  = new System.Drawing.Point(96, 179);
            this.tbGame.TabIndex = 8;
            this.tbGame.Enabled = false;
            this.tbGame.Name = "tbGame";
            this.tbDescription.Size  = new System.Drawing.Size(209, 21);
            this.tbDescription.Location  = new System.Drawing.Point(96, 7);
            this.tbDescription.TabIndex = 0;
            this.tbDescription.Enabled = false;
            this.tbDescription.Name = "tbDescription";
            this.btnSave.Size  = new System.Drawing.Size(65, 25);
            this.btnSave.Location  = new System.Drawing.Point(88, 206);
            this.btnSave.Text = "&OK";
            this.btnSave.Click += new System.EventHandler(this.btnSaveClick);
            this.btnSave.TabIndex = 9;
            this.btnSave.Name = "btnSave";
            this.btnSave.Enabled = false;
            this.btnSave.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.btnCancel.Size  = new System.Drawing.Size(65, 25);
            this.btnCancel.Location  = new System.Drawing.Point(168, 206);
            this.btnCancel.Text = "&Cancel";
            this.btnCancel.Click += new System.EventHandler(this.btnCancelClick);
            this.btnCancel.TabIndex = 10;
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Enabled = false;
            this.btnCancel.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.cbGames.Size  = new System.Drawing.Size(209, 21);
            this.cbGames.Location  = new System.Drawing.Point(64, 16);
            this.cbGames.TabIndex = 1;
            this.cbGames.SelectedIndexChanged += new System.EventHandler(this.cbGamesChange);
            this.cbGames.Enabled = true;
            this.cbGames.ItemHeight = 13;
            this.cbGames.Name = "cbGames";
            this.btnAdd.Size  = new System.Drawing.Size(65, 25);
            this.btnAdd.Location  = new System.Drawing.Point(64, 48);
            this.btnAdd.Text = "&Add";
            this.btnAdd.Click += new System.EventHandler(this.btnAddClick);
            this.btnAdd.TabIndex = 2;
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.Enabled = true;
            this.btnAdd.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.btnDelete.Size  = new System.Drawing.Size(65, 25);
            this.btnDelete.Location  = new System.Drawing.Point(136, 48);
            this.btnDelete.Text = "&Delete";
            this.btnDelete.Click += new System.EventHandler(this.btnDeleteClick);
            this.btnDelete.TabIndex = 3;
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.Enabled = true;
            this.btnDelete.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.btnEdit.Size  = new System.Drawing.Size(65, 25);
            this.btnEdit.Location  = new System.Drawing.Point(208, 48);
            this.btnEdit.Text = "&Edit";
            this.btnEdit.Click += new System.EventHandler(this.btnEditClick);
            this.btnEdit.TabIndex = 4;
            this.btnEdit.Name = "btnEdit";
            this.btnEdit.Enabled = true;
            this.btnEdit.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.tabProgram.Size  = new System.Drawing.Size(0, 0);
            this.tabProgram.Location  = new System.Drawing.Point(0, 0);
            this.tabProgram.SuspendLayout();
            this.tabProgram.Text = "Program";
            this.tabProgram.Enabled = true;
            this.tabProgram.ImageIndex = 4;
            this.tabProgram.Name = "tabProgram";
            this.Label2.Size  = new System.Drawing.Size(140, 13);
            this.Label2.Location  = new System.Drawing.Point(16, 24);
            this.Label2.Text = "Listen for connections on port";
            this.Label2.Enabled = true;
            this.Label2.Name = "Label2";
            this.Label11.Size  = new System.Drawing.Size(138, 13);
            this.Label11.Location  = new System.Drawing.Point(16, 48);
            this.Label11.Text = "Terminal menu activation key";
            this.Label11.Enabled = true;
            this.Label11.Name = "Label11";
            this.Label10.Size  = new System.Drawing.Size(100, 13);
            this.Label10.Location  = new System.Drawing.Point(16, 72);
            this.Label10.Text = "Maximum bubble size";
            this.Label10.Enabled = true;
            this.Label10.Name = "Label10";
            this.cbAcceptExternal.Size  = new System.Drawing.Size(169, 17);
            this.cbAcceptExternal.Location  = new System.Drawing.Point(16, 120);
            this.cbAcceptExternal.TabIndex = 3;
            this.cbAcceptExternal.Text = "Accept external connections";
            this.cbAcceptExternal.Enabled = true;
            this.cbAcceptExternal.Name = "cbAcceptExternal";
            this.cbBroadcast.Size  = new System.Drawing.Size(241, 17);
            this.cbBroadcast.Location  = new System.Drawing.Point(16, 144);
            this.cbBroadcast.TabIndex = 4;
            this.cbBroadcast.CheckState = System.Windows.Forms.CheckState.Checked;
            this.cbBroadcast.Text = "Broadcast a message when a client connects";
            this.cbBroadcast.Checked = true;
            this.cbBroadcast.Name = "cbBroadcast";
            this.cbBroadcast.Enabled = true;
            this.tbListenPort.Size  = new System.Drawing.Size(57, 21);
            this.tbListenPort.Location  = new System.Drawing.Point(168, 22);
            this.tbListenPort.TabIndex = 0;
            this.tbListenPort.Text = "23";
            this.tbListenPort.Enabled = true;
            this.tbListenPort.Name = "tbListenPort";
            this.tbMenuKey.Size  = new System.Drawing.Size(25, 21);
            this.tbMenuKey.Location  = new System.Drawing.Point(168, 46);
            this.tbMenuKey.Font  = new System.Drawing.Font("MS Sans Serif", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point ,((byte)(1)));
            this.tbMenuKey.Enabled = true;
            this.tbMenuKey.TabIndex = 1;
            this.tbMenuKey.ModifiedChanged += new System.EventHandler(this.tbMenuKeyChange);
            this.tbMenuKey.Name = "tbMenuKey";
            this.tbMenuKey.Text = "$";
            this.cbReconnect.Size  = new System.Drawing.Size(169, 17);
            this.cbReconnect.Location  = new System.Drawing.Point(16, 168);
            this.cbReconnect.TabIndex = 5;
            this.cbReconnect.Text = "Automatically reconnect";
            this.cbReconnect.Enabled = true;
            this.cbReconnect.Name = "cbReconnect";
            this.cbCache.Size  = new System.Drawing.Size(209, 17);
            this.cbCache.Location  = new System.Drawing.Point(16, 192);
            this.cbCache.TabIndex = 6;
            this.cbCache.CheckState = System.Windows.Forms.CheckState.Checked;
            this.cbCache.Text = "Cache database in available memory";
            this.cbCache.Checked = true;
            this.cbCache.Name = "cbCache";
            this.cbCache.Enabled = true;
            this.tbBubbleSize.Size  = new System.Drawing.Size(57, 21);
            this.tbBubbleSize.Location  = new System.Drawing.Point(168, 70);
            this.tbBubbleSize.TabIndex = 2;
            this.tbBubbleSize.Text = "30";
            this.tbBubbleSize.Enabled = true;
            this.tbBubbleSize.Name = "tbBubbleSize";
            this.cbLocalEcho.Size  = new System.Drawing.Size(153, 17);
            this.cbLocalEcho.Location  = new System.Drawing.Point(16, 216);
            this.cbLocalEcho.TabIndex = 7;
            this.cbLocalEcho.Text = "Local echo of outgoing text";
            this.cbLocalEcho.Enabled = true;
            this.cbLocalEcho.Name = "cbLocalEcho";
            this.tabLogging.Size  = new System.Drawing.Size(0, 0);
            this.tabLogging.Location  = new System.Drawing.Point(0, 0);
            this.tabLogging.SuspendLayout();
            this.tabLogging.Text = "Logging";
            this.tabLogging.Enabled = true;
            this.tabLogging.ImageIndex = 5;
            this.tabLogging.Name = "tabLogging";
            this.Label9.Size  = new System.Drawing.Size(165, 13);
            this.Label9.Location  = new System.Drawing.Point(16, 112);
            this.Label9.Text = "Shorten all playback delays above ";
            this.Label9.Enabled = true;
            this.Label9.Name = "Label9";
            this.Label20.Size  = new System.Drawing.Size(40, 13);
            this.Label20.Location  = new System.Drawing.Point(230, 112);
            this.Label20.Text = "seconds";
            this.Label20.Enabled = true;
            this.Label20.Name = "Label20";
            this.cbLog.Size  = new System.Drawing.Size(225, 17);
            this.cbLog.Location  = new System.Drawing.Point(16, 16);
            this.cbLog.TabIndex = 0;
            this.cbLog.Text = "Log data according to selected database";
            this.cbLog.Enabled = true;
            this.cbLog.Name = "cbLog";
            this.cbLogANSI.Size  = new System.Drawing.Size(161, 17);
            this.cbLogANSI.Location  = new System.Drawing.Point(48, 40);
            this.cbLogANSI.TabIndex = 1;
            this.cbLogANSI.Text = "Log ANSI codes";
            this.cbLogANSI.Enabled = true;
            this.cbLogANSI.Name = "cbLogANSI";
            this.cbLogBinary.Size  = new System.Drawing.Size(289, 17);
            this.cbLogBinary.Location  = new System.Drawing.Point(48, 64);
            this.cbLogBinary.TabIndex = 2;
            this.cbLogBinary.Text = "Log as binary (allows extra logging and capture features)";
            this.cbLogBinary.Enabled = true;
            this.cbLogBinary.Name = "cbLogBinary";
            this.cbNotifyLogDelay.Size  = new System.Drawing.Size(241, 17);
            this.cbNotifyLogDelay.Location  = new System.Drawing.Point(16, 144);
            this.cbNotifyLogDelay.TabIndex = 3;
            this.cbNotifyLogDelay.Text = "Notify when a delay has been shortened";
            this.cbNotifyLogDelay.Enabled = true;
            this.cbNotifyLogDelay.Name = "cbNotifyLogDelay";
            this.tbShortenDelay.Size  = new System.Drawing.Size(41, 21);
            this.tbShortenDelay.Location  = new System.Drawing.Point(184, 110);
            this.tbShortenDelay.TabIndex = 4;
            this.tbShortenDelay.Text = "0";
            this.tbShortenDelay.Enabled = true;
            this.tbShortenDelay.Name = "tbShortenDelay";
            this.tabAutoRun.Size  = new System.Drawing.Size(0, 0);
            this.tabAutoRun.Location  = new System.Drawing.Point(0, 0);
            this.tabAutoRun.SuspendLayout();
            this.tabAutoRun.Text = "Auto Run";
            this.tabAutoRun.Enabled = true;
            this.tabAutoRun.ImageIndex = 3;
            this.tabAutoRun.Name = "tabAutoRun";
            this.lbAutoRun.Size  = new System.Drawing.Size(313, 193);
            this.lbAutoRun.Location  = new System.Drawing.Point(24, 96);
            this.lbAutoRun.TabIndex = 0;
            this.lbAutoRun.Enabled = true;
            this.lbAutoRun.ItemHeight = 13;
            this.lbAutoRun.Name = "lbAutoRun";
            this.memHint3.Size  = new System.Drawing.Size(313, 33);
            this.memHint3.Location  = new System.Drawing.Point(24, 8);
            this.memHint3.Lines =  new string[] { 
                "Add a script to the list below to make the script auto-launch on ",
                "program startup",
                };
            this.memHint3.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.memHint3.Multiline = true;
            this.memHint3.TabIndex = 1;
            this.memHint3.Name = "memHint3";
            this.memHint3.Enabled = true;
            this.memHint3.ReadOnly = true;
            this.btnAddAutoRun.Size  = new System.Drawing.Size(89, 25);
            this.btnAddAutoRun.Location  = new System.Drawing.Point(80, 64);
            this.btnAddAutoRun.Text = "&Add Script";
            this.btnAddAutoRun.Click += new System.EventHandler(this.btnAddAutoRunClick);
            this.btnAddAutoRun.TabIndex = 2;
            this.btnAddAutoRun.Name = "btnAddAutoRun";
            this.btnAddAutoRun.Enabled = true;
            this.btnAddAutoRun.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.btnRemoveAutoRun.Size  = new System.Drawing.Size(89, 25);
            this.btnRemoveAutoRun.Location  = new System.Drawing.Point(184, 64);
            this.btnRemoveAutoRun.Text = "&Remove Script";
            this.btnRemoveAutoRun.Click += new System.EventHandler(this.btnRemoveAutoRunClick);
            this.btnRemoveAutoRun.TabIndex = 3;
            this.btnRemoveAutoRun.Name = "btnRemoveAutoRun";
            this.btnRemoveAutoRun.Enabled = true;
            this.btnRemoveAutoRun.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.tabUser.Size  = new System.Drawing.Size(0, 0);
            this.tabUser.Location  = new System.Drawing.Point(0, 0);
            this.tabUser.SuspendLayout();
            this.tabUser.Visible = false;
            this.tabUser.Text = "Registration";
            this.tabUser.Enabled = true;
            this.tabUser.ImageIndex = 5;
            this.tabUser.Name = "tabUser";
            this.Label18.Size  = new System.Drawing.Size(36, 13);
            this.Label18.Location  = new System.Drawing.Point(48, 88);
            this.Label18.Text = "User ID";
            this.Label18.Enabled = true;
            this.Label18.Name = "Label18";
            this.Label19.Size  = new System.Drawing.Size(77, 13);
            this.Label19.Location  = new System.Drawing.Point(48, 120);
            this.Label19.Text = "Registration Key";
            this.Label19.Enabled = true;
            this.Label19.Name = "Label19";
            this.Label4.Size  = new System.Drawing.Size(233, 26);
            this.Label4.Location  = new System.Drawing.Point(72, 160);
            this.Label4.Text = "Authenticate this key when TWX Proxy is loaded (Required for usage)";
            this.Label4.Enabled = true;
            this.Label4.Name = "Label4";
            this.Label5.Size  = new System.Drawing.Size(266, 26);
            this.Label5.Location  = new System.Drawing.Point(40, 248);
            this.Label5.Text = "Note: Any registration keys for TWX Proxy v1.0x are not compatible with this version and must be upgraded first.";
            this.Label5.Enabled = true;
            this.Label5.Name = "Label5";
            this.memHint2.Size  = new System.Drawing.Size(345, 57);
            this.memHint2.Location  = new System.Drawing.Point(8, 8);
            this.memHint2.Font  = new System.Drawing.Font("MS Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point ,((byte)(1)));
            this.memHint2.Lines =  new string[] { 
                "Your user ID and registration key are required if you wish to make use of ",
                "the powerful pack2 script subroutines.  You can obtain a registration for ",
                "$30 US at http://www.twxproxy.com",
                };
            this.memHint2.Multiline = true;
            this.memHint2.ReadOnly = true;
            this.memHint2.TabIndex = 0;
            this.memHint2.Name = "memHint2";
            this.memHint2.Enabled = true;
            this.memHint2.BackColor = System.Drawing.SystemColors.AppWorkspace;
            this.tbUser.Size  = new System.Drawing.Size(73, 21);
            this.tbUser.Location  = new System.Drawing.Point(136, 84);
            this.tbUser.TabIndex = 1;
            this.tbUser.Text = "0000000000";
            this.tbUser.Enabled = true;
            this.tbUser.ModifiedChanged += new System.EventHandler(this.tbUserChange);
            this.tbUser.Name = "tbUser";
            this.tbRegKey.Size  = new System.Drawing.Size(137, 21);
            this.tbRegKey.Location  = new System.Drawing.Point(136, 116);
            this.tbRegKey.TabIndex = 2;
            this.tbRegKey.ModifiedChanged += new System.EventHandler(this.tbUserChange);
            this.tbRegKey.Enabled = true;
            this.tbRegKey.Name = "tbRegKey";
            this.cbAuthenticate.Size  = new System.Drawing.Size(17, 17);
            this.cbAuthenticate.Location  = new System.Drawing.Point(48, 160);
            this.cbAuthenticate.TabIndex = 3;
            this.cbAuthenticate.Enabled = true;
            this.cbAuthenticate.Name = "cbAuthenticate";
            this.btnUpgrade.Size  = new System.Drawing.Size(161, 25);
            this.btnUpgrade.Location  = new System.Drawing.Point(96, 280);
            this.btnUpgrade.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.btnUpgrade.Text = "&Upgrade Old Registration";
            this.btnUpgrade.TabIndex = 4;
            this.btnUpgrade.Enabled = true;
            this.btnUpgrade.Name = "btnUpgrade";
            this.tabProxy.Size  = new System.Drawing.Size(0, 0);
            this.tabProxy.Location  = new System.Drawing.Point(0, 0);
            this.tabProxy.SuspendLayout();
            this.tabProxy.Visible = false;
            this.tabProxy.Text = "Auth Proxy";
            this.tabProxy.Enabled = true;
            this.tabProxy.ImageIndex = 4;
            this.tabProxy.Name = "tabProxy";
            this.Label6.Size  = new System.Drawing.Size(225, 13);
            this.Label6.Location  = new System.Drawing.Point(56, 24);
            this.Label6.Text = "Use HTTP Proxy for Registration Authentication";
            this.Label6.Enabled = true;
            this.Label6.Name = "Label6";
            this.Label7.Size  = new System.Drawing.Size(67, 13);
            this.Label7.Location  = new System.Drawing.Point(40, 88);
            this.Label7.Text = "Proxy Address";
            this.Label7.Enabled = true;
            this.Label7.Name = "Label7";
            this.Label8.Size  = new System.Drawing.Size(48, 13);
            this.Label8.Location  = new System.Drawing.Point(40, 120);
            this.Label8.Text = "Proxy Port";
            this.Label8.Enabled = true;
            this.Label8.Name = "Label8";
            this.cbUseAuthProxy.Size  = new System.Drawing.Size(17, 17);
            this.cbUseAuthProxy.Location  = new System.Drawing.Point(35, 23);
            this.cbUseAuthProxy.TabIndex = 0;
            this.cbUseAuthProxy.Enabled = true;
            this.cbUseAuthProxy.Name = "cbUseAuthProxy";
            this.tbProxyAddress.Size  = new System.Drawing.Size(121, 21);
            this.tbProxyAddress.Location  = new System.Drawing.Point(128, 85);
            this.tbProxyAddress.TabIndex = 1;
            this.tbProxyAddress.ModifiedChanged += new System.EventHandler(this.tbUserChange);
            this.tbProxyAddress.Enabled = false;
            this.tbProxyAddress.Name = "tbProxyAddress";
            this.tbProxyPort.Size  = new System.Drawing.Size(57, 21);
            this.tbProxyPort.Location  = new System.Drawing.Point(128, 116);
            this.tbProxyPort.TabIndex = 2;
            this.tbProxyPort.Text = "8080";
            this.tbProxyPort.Enabled = false;
            this.tbProxyPort.ModifiedChanged += new System.EventHandler(this.tbUserChange);
            this.tbProxyPort.Name = "tbProxyPort";
            this.btnOKMain.Size  = new System.Drawing.Size(73, 25);
            this.btnOKMain.Location  = new System.Drawing.Point(216, 352);
            this.btnOKMain.Text = "&OK";
            this.btnOKMain.Click += new System.EventHandler(this.btnOKMainClick);
            this.btnOKMain.TabIndex = 1;
            this.btnOKMain.Name = "btnOKMain";
            this.btnOKMain.Enabled = true;
            this.btnOKMain.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.btnCancelMain.Size  = new System.Drawing.Size(73, 25);
            this.btnCancelMain.Location  = new System.Drawing.Point(296, 352);
            this.btnCancelMain.Text = "&Cancel";
            this.btnCancelMain.Click += new System.EventHandler(this.btnCancelMainClick);
            this.btnCancelMain.TabIndex = 2;
            this.btnCancelMain.Name = "btnCancelMain";
            this.btnCancelMain.Enabled = true;
            this.btnCancelMain.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.OpenDialog.Filter = "TW script (*.ts, *.ets, *.es)|*.ts;*.ets;*.cts";
            this.tmrReg.Interval = 10000;
            this.tmrReg.Tick += new System.EventHandler(this.tmrRegTimer);
            this.tmrReg.Enabled = false;
            this.Panel1.Controls.Add(Label12);
            this.Panel1.Controls.Add(Label3);
            this.Panel1.Controls.Add(Label1);
            this.Panel1.Controls.Add(Label13);
            this.Panel1.Controls.Add(Label14);
            this.Panel1.Controls.Add(Label15);
            this.Panel1.Controls.Add(Label16);
            this.Panel1.Controls.Add(Label17);
            this.Panel1.Controls.Add(tbHost);
            this.Panel1.Controls.Add(tbPort);
            this.Panel1.Controls.Add(tbSectors);
            this.Panel1.Controls.Add(tbLoginScript);
            this.Panel1.Controls.Add(cbUseLogin);
            this.Panel1.Controls.Add(tbLoginName);
            this.Panel1.Controls.Add(tbPassword);
            this.Panel1.Controls.Add(tbGame);
            this.Panel1.Controls.Add(tbDescription);
            this.Panel1.Controls.Add(btnSave);
            this.Panel1.Controls.Add(btnCancel);
            this.Panel1.ResumeLayout(false);
            this.tabServer.Controls.Add(Panel1);
            this.tabServer.Controls.Add(cbGames);
            this.tabServer.Controls.Add(btnAdd);
            this.tabServer.Controls.Add(btnDelete);
            this.tabServer.Controls.Add(btnEdit);
            this.tabServer.ResumeLayout(false);
            this.tabProgram.Controls.Add(Label2);
            this.tabProgram.Controls.Add(Label11);
            this.tabProgram.Controls.Add(Label10);
            this.tabProgram.Controls.Add(cbAcceptExternal);
            this.tabProgram.Controls.Add(cbBroadcast);
            this.tabProgram.Controls.Add(tbListenPort);
            this.tabProgram.Controls.Add(tbMenuKey);
            this.tabProgram.Controls.Add(cbReconnect);
            this.tabProgram.Controls.Add(cbCache);
            this.tabProgram.Controls.Add(tbBubbleSize);
            this.tabProgram.Controls.Add(cbLocalEcho);
            this.tabProgram.ResumeLayout(false);
            this.tabLogging.Controls.Add(Label9);
            this.tabLogging.Controls.Add(Label20);
            this.tabLogging.Controls.Add(cbLog);
            this.tabLogging.Controls.Add(cbLogANSI);
            this.tabLogging.Controls.Add(cbLogBinary);
            this.tabLogging.Controls.Add(cbNotifyLogDelay);
            this.tabLogging.Controls.Add(tbShortenDelay);
            this.tabLogging.ResumeLayout(false);
            this.tabAutoRun.Controls.Add(lbAutoRun);
            this.tabAutoRun.Controls.Add(memHint3);
            this.tabAutoRun.Controls.Add(btnAddAutoRun);
            this.tabAutoRun.Controls.Add(btnRemoveAutoRun);
            this.tabAutoRun.ResumeLayout(false);
            this.tabUser.Controls.Add(Label18);
            this.tabUser.Controls.Add(Label19);
            this.tabUser.Controls.Add(Label4);
            this.tabUser.Controls.Add(Label5);
            this.tabUser.Controls.Add(memHint2);
            this.tabUser.Controls.Add(tbUser);
            this.tabUser.Controls.Add(tbRegKey);
            this.tabUser.Controls.Add(cbAuthenticate);
            this.tabUser.Controls.Add(btnUpgrade);
            this.tabUser.ResumeLayout(false);
            this.tabProxy.Controls.Add(Label6);
            this.tabProxy.Controls.Add(Label7);
            this.tabProxy.Controls.Add(Label8);
            this.tabProxy.Controls.Add(cbUseAuthProxy);
            this.tabProxy.Controls.Add(tbProxyAddress);
            this.tabProxy.Controls.Add(tbProxyPort);
            this.tabProxy.ResumeLayout(false);
            this.PageControl.Controls.Add(tabServer);
            this.PageControl.Controls.Add(tabProgram);
            this.PageControl.Controls.Add(tabLogging);
            this.PageControl.Controls.Add(tabAutoRun);
            this.PageControl.Controls.Add(tabUser);
            this.PageControl.Controls.Add(tabProxy);
            this.PageControl.ResumeLayout(false);
            this.Controls.Add(PageControl);
            this.Controls.Add(btnOKMain);
            this.Controls.Add(btnCancelMain);
            this.ResumeLayout(false);
        }
#endregion

    }
}
