copy "..\..\..\..\..\modes\defense\ig.*" "modes\defense\ig.*"
copy "..\..\..\..\..\modes\defense\saveme.*" "modes\defense\saveme.*"
copy "..\..\..\..\..\modes\resource\lsd.*" "modes\resource\lsd.*"
copy "..\..\..\..\..\modes\resource\movefig.*" "resource\movefig.*"
copy "..\..\..\..\..\modes\resource\moveship.*" "resource\moveship.*"
copy "..\..\..\..\..\modes\resource\strip.*" "modes\resource\strip.*"
copy "..\..\..\..\..\modes\data\ztm.*" "modes\data\ztm.*"
copy "..\..\..\..\..\commands\data\param.*" "commands\data\param.*"
copy "..\..\..\..\..\modes\data\sentinel.*" "modes\data\sentinel.*"
copy "..\..\..\..\..\modes\cashing\sst.*" "modes\cashing\sst.*"
copy "..\..\..\..\..\modes\cashing\sdt.*" "modes\cashing\sdt.*"
copy "..\..\..\..\..\modes\cashing\bbb.*" "modes\cashing\bbb.*"
copy "..\..\..\..\..\modes\cashing\furb.*" "modes\cashing\furb.*"
copy "..\..\..\..\..\modes\cashing\wppt.*" "modes\cashing\wppt.*"
copy "..\..\..\..\..\commands\data\disp.*" "commands\data\disp.*"
copy "..\..\..\..\..\commands\data\setparms.*" "commands\data\setparms.*"
copy "..\..\..\..\..\commands\data\setparam.*" "commands\data\setparam.*"
copy "..\..\..\..\..\commands\data\holo.*" "commands\data\holo.*"
copy "..\..\..\..\..\commands\data\dscan.*" "commands\data\dscan.*"
copy "..\..\..\..\..\commands\data\cim.*" "commands\data\cim.*"
copy "..\..\..\..\..\commands\data\slist.*" "commands\data\slist.*"
copy "..\..\..\..\..\commands\data\plist.*" "commands\data\plist.*"
copy "..\..\..\..\..\commands\data\find.*" "commands\data\find.*"
copy "..\..\..\..\..\commands\data\deploy.*" "commands\data\deploy.*"
copy "..\..\..\..\..\commands\data\busts.*" "commands\data\busts.*"
copy "..\..\..\..\..\commands\data\clearbusts.*" "commands\data\clearbusts.*"
copy "..\..\..\..\..\commands\data\corp_info.*" "commands\data\corp_info.*"
copy "..\..\..\..\..\commands\data\course.*" "commands\data\course.*"
copy "..\..\..\..\..\commands\data\pscan.*" "commands\data\pscan.*"
copy "..\..\..\..\..\commands\data\time.*" "commands\data\time.*"
copy "..\..\..\..\..\commands\data\status.*" "commands\data\status.*"
copy "..\..\..\..\..\commands\data\sector.*" "commands\data\sector.*"
copy "..\..\..\..\..\commands\data\overload.*" "commands\data\overload.*"
copy "..\..\..\..\..\commands\data\avoids.*" "commands\data\avoids.*"
copy "..\..\..\..\..\commands\data\getvar.*" "commands\data\getvar.*"
copy "..\..\..\..\..\commands\data\setvar.*" "commands\data\setvar.*"
copy "..\..\..\..\..\commands\data\ping.*" "commands\data\ping.*"
copy "..\..\..\..\..\commands\data\select.*" "commands\data\select.*"
copy "..\..\..\..\..\commands\data\history.*" "commands\data\history.*"
copy "..\..\..\..\..\commands\general\pwarp.*" "commands\general\pwarp.*"
copy "..\..\..\..\..\commands\general\photon.*" "commands\general\photon.*"
copy "..\..\..\..\..\commands\general\reboot.*" "commands\general\reboot.*"
copy "..\..\..\..\..\commands\general\relog.*" "commands\general\relog.*"
copy "..\..\..\..\..\commands\general\xport.*" "commands\general\xport.*"
copy "..\..\..\..\..\commands\general\land.*" "commands\general\land.*"
copy "..\..\..\..\..\commands\general\nmac.*" "commands\general\nmac.*"
copy "..\..\..\..\..\commands\general\subspace.*" "commands\general\subspace.*"
copy "..\..\..\..\..\commands\general\with.*" "commands\general\with.*"
copy "..\..\..\..\..\commands\general\mac.*" "commands\general\mac.*"
copy "..\..\..\..\..\commands\general\dep.*" "commands\general\dep.*"
copy "..\..\..\..\..\commands\general\tow.*" "commands\general\tow.*"
copy "..\..\..\..\..\commands\general\bwarp.*" "commands\general\bwarp.*"
copy "..\..\..\..\..\commands\general\corp.*" "commands\general\corp.*"
copy "..\..\..\..\..\commands\general\twarp.*" "commands\general\twarp.*"
copy "..\..\..\..\..\commands\general\unlock.*" "commands\general\unlock.*"
copy "..\..\..\..\..\commands\general\topoff.*" "commands\general\topoff.*"
copy "..\..\..\..\..\commands\general\page.*" "commands\general\page.*"
copy "..\..\..\..\..\commands\general\callout.*" "commands\general\callout.*"
copy "..\..\..\..\..\commands\defense\call.*" "commands\defense\call.*"
copy "..\..\..\..\..\commands\defense\_macro_kit.*" "commands\defense\_macro_kit.*"
copy "..\..\..\..\..\commands\defense\evac.*" "commands\defense\evac.*"
copy "..\..\..\..\..\commands\resource\_dock_shopper.*" "commands\resource\_dock_shopper.*"
copy "..\..\..\..\..\commands\cashing\mega.*" "commands\cashing\mega.*"
copy "..\..\..\..\..\commands\cashing\tricon.ts" "commands\cashing\tricon.*"
copy "..\..\..\..\..\commands\general\tow.*" "commands\general\tow.*"
copy "..\..\..\..\..\commands\grid\port.*" "commands\grid\port.*"
copy "..\..\..\..\..\commands\grid\update.*" "commands\grid\update.*"
copy "..\..\..\..\..\commands\general\help.*" "commands\general\help.*"
copy "..\..\..\..\..\commands\cashing\neg.*" "commands\cashing\neg.*"
copy "..\..\..\..\..\commands\cashing\rob.*" "commands\cashing\rob.*"
copy "..\..\..\..\..\commands\cashing\ppt.*" "commands\cashing\ppt.*"
copy "..\..\..\..\..\commands\grid\clear.*" "commands\grid\clear.*"
copy "..\..\..\..\..\commands\grid\xenter.*" "commands\grid\xenter.*"
copy "..\..\..\..\..\commands\grid\xenter.*" "commands\grid\exit.*"
copy "..\..\..\..\..\commands\grid\pgrid.*" "commands\grid\pgrid.*"
copy "..\..\..\..\..\commands\grid\climp.*" "commands\grid\climp.*"
copy "..\..\..\..\..\commands\grid\cmine.*" "commands\grid\cmine.*"
copy "..\..\..\..\..\daemons\comms.*" "daemons\comms.*"
copy "..\..\..\..\..\daemons\watcher.*" "daemons\watcher.*"
copy "..\..\..\..\..\daemons\ignore.*" "daemons\ignore.*"
copy "..\..\..\..\..\daemons\stats.*" "daemons\stats.*"
copy "..\..\..\..\..\daemons\chat.*" "daemons\chat.*"
copy "..\..\..\..\..\daemons\ephaggle.*" "daemons\ephaggle.*"
copy "..\..\..\..\..\daemons\viewscreen.*" "daemons\viewscreen.*"
copy "..\..\..\..\..\daemons\online.*" "daemons\online.*"
copy "..\..\..\..\..\startups\viewscreen.*" "startups\viewscreen.*"
copy "..\..\..\..\..\startups\watcher.*" "startups\watcher.*"
copy "..\..\..\..\..\startups\chat.*" "startups\chat.*"
copy "..\..\..\..\..\startups\viewscreen.*" "startups\viewscreen.*"
copy "..\..\..\..\..\source\bot_includes\bot\connectivity.ts" "source\bot_includes\bot\connectivity.ts"
copy "..\..\..\..\..\source\bot_includes\bot\listener.ts" "source\bot_includes\bot\listener.ts"
copy "..\..\..\..\..\source\bot_includes\bot\user_interface.ts" "source\bot_includes\bot\user_interface.ts"
xcopy "..\..\..\..\..\source\bot_includes\player" "source\bot_includes\player" /E
xcopy "..\..\..\..\..\source\bot_includes\planet" "source\bot_includes\planet" /E
xcopy "..\..\..\..\..\source\bot_includes\map" "source\bot_includes\map" /E
xcopy "..\..\..\..\..\source\bot_includes\ship" "source\bot_includes\ship" /E
xcopy "..\..\..\..\..\source\bot_includes\game" "source\bot_includes\game" /E
xcopy "..\..\..\..\..\source\module_includes\bot" "source\module_includes\bot" /E
xcopy "..\..\..\..\..\source\module_includes\deploy" "source\module_includes\deploy" /E
xcopy "..\..\..\..\..\source\module_includes\update" "source\module_includes\update" /E
timeout 20

