#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
:planetnames~make_planet_array
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
setarray $planetnames~planet_names 1000
setvar $planetnames~planet_names[1] "LoneStar's Circle"
setvar $planetnames~planet_names[2] "Manton Outpost"
setvar $planetnames~planet_names[3] "Triax Annex"
setvar $planetnames~planet_names[4] "New Ovid"
setvar $planetnames~planet_names[5] "Napier Minor"
setvar $planetnames~planet_names[6] "New Barite"
setvar $planetnames~planet_names[7] "Agamotto II"
setvar $planetnames~planet_names[8] "Poincare Thunder"
setvar $planetnames~planet_names[9] "Camelopardus"
setvar $planetnames~planet_names[10] "Ticonderoga Annex"
setvar $planetnames~planet_names[11] "Cana Annex"
setvar $planetnames~planet_names[12] "Rifts II"
setvar $planetnames~planet_names[13] "Arago Annex"
setvar $planetnames~planet_names[14] "Grosseteste Primus"
setvar $planetnames~planet_names[15] "Lablon Minor"
setvar $planetnames~planet_names[16] "Ampilean Minor"
setvar $planetnames~planet_names[17] "Pappus II"
setvar $planetnames~planet_names[18] "Buddha Gaya II"
setvar $planetnames~planet_names[19] "Phlogiston Major"
setvar $planetnames~planet_names[20] "Pilar Dawn"
setvar $planetnames~planet_names[21] "Vergil"
setvar $planetnames~planet_names[22] "Zennor Primus"
setvar $planetnames~planet_names[23] "Vigara Outpost"
setvar $planetnames~planet_names[24] "l'Hopital"
setvar $planetnames~planet_names[25] "Axe-Gonne Annex"
setvar $planetnames~planet_names[26] "New Plaskett"
setvar $planetnames~planet_names[27] "Quadrono Fury"
setvar $planetnames~planet_names[28] "Cuirass Annex"
setvar $planetnames~planet_names[29] "Bendor II"
setvar $planetnames~planet_names[30] "Catuz II"
setvar $planetnames~planet_names[31] "New Barazole"
setvar $planetnames~planet_names[32] "Burgundy Outpost"
setvar $planetnames~planet_names[33] "Tibanna Annex"
setvar $planetnames~planet_names[34] "New Vesta"
setvar $planetnames~planet_names[35] "Aerobe Minor"
setvar $planetnames~planet_names[36] "Cornu Primus"
setvar $planetnames~planet_names[37] "Heguz Outpost"
setvar $planetnames~planet_names[38] "Khrytarrm II"
setvar $planetnames~planet_names[39] "Zodiac"
setvar $planetnames~planet_names[40] "Bevey Primus"
setvar $planetnames~planet_names[41] "Pauli Stars"
setvar $planetnames~planet_names[42] "Axanar Outpost"
setvar $planetnames~planet_names[43] "Veialstroum"
setvar $planetnames~planet_names[44] "Dedendum"
setvar $planetnames~planet_names[45] "Parthenon Outpost"
setvar $planetnames~planet_names[46] "Ahzdar Primus"
setvar $planetnames~planet_names[47] "Tionale Minor"
setvar $planetnames~planet_names[48] "Fomalhaut Minor"
setvar $planetnames~planet_names[49] "Calandra Index"
setvar $planetnames~planet_names[50] "New Drude"
setvar $planetnames~planet_names[51] "Troi Primus"
setvar $planetnames~planet_names[52] "Tourmaline Primus"
setvar $planetnames~planet_names[53] "Adurol"
setvar $planetnames~planet_names[54] "Zaibon Outpost"
setvar $planetnames~planet_names[55] "Cipango Annex"
setvar $planetnames~planet_names[56] "Saxbury Annex"
setvar $planetnames~planet_names[57] "New Oomaru"
setvar $planetnames~planet_names[58] "Weiland Minor"
setvar $planetnames~planet_names[59] "Bertian II"
setvar $planetnames~planet_names[60] "Strahd Outpost"
setvar $planetnames~planet_names[61] "Hallwachs Primus"
setvar $planetnames~planet_names[62] "Fabrina Primus"
setvar $planetnames~planet_names[63] "Ovid"
setvar $planetnames~planet_names[64] "Campell II"
setvar $planetnames~planet_names[65] "Osnabruck Major"
setvar $planetnames~planet_names[66] "Merrimac Minor"
setvar $planetnames~planet_names[67] "Toscanelli Major"
setvar $planetnames~planet_names[68] "Hoover Minor"
setvar $planetnames~planet_names[69] "Pangelinan Outpost"
setvar $planetnames~planet_names[70] "Bethune Minor"
setvar $planetnames~planet_names[71] "Fafnir"
setvar $planetnames~planet_names[72] "Gideon Outpost"
setvar $planetnames~planet_names[73] "Tajarhi Primus"
setvar $planetnames~planet_names[74] "Catoblepas Major"
setvar $planetnames~planet_names[75] "Steel Major"
setvar $planetnames~planet_names[76] "Grey Mist"
setvar $planetnames~planet_names[77] "Boreas Minor"
setvar $planetnames~planet_names[78] "New Entrailia"
setvar $planetnames~planet_names[79] "Saturn Primus"
setvar $planetnames~planet_names[80] "Aerolone Major"
setvar $planetnames~planet_names[81] "Camelot Primus"
setvar $planetnames~planet_names[82] "Copus Outpost"
setvar $planetnames~planet_names[83] "Bedoz Whispers"
setvar $planetnames~planet_names[84] "Czar'ak II"
setvar $planetnames~planet_names[85] "Mastro"
setvar $planetnames~planet_names[86] "Venus Outpost"
setvar $planetnames~planet_names[87] "New Io"
setvar $planetnames~planet_names[88] "Tsox II"
setvar $planetnames~planet_names[89] "Acropolis II"
setvar $planetnames~planet_names[90] "CSM-101 Annex"
setvar $planetnames~planet_names[91] "Apian II"
setvar $planetnames~planet_names[92] "New Brodie"
setvar $planetnames~planet_names[93] "Clone Annex"
setvar $planetnames~planet_names[94] "K'hotan Major"
setvar $planetnames~planet_names[95] "Indusium Primus"
setvar $planetnames~planet_names[96] "Javelle Minor"
setvar $planetnames~planet_names[97] "Gold Major"
setvar $planetnames~planet_names[98] "New Poincare"
setvar $planetnames~planet_names[99] "New Ohm"
setvar $planetnames~planet_names[100] "Jeeves"
setvar $planetnames~planet_names[101] "Ahriman Primus"
setvar $planetnames~planet_names[102] "Bajor II"
setvar $planetnames~planet_names[103] "Pickering Primus"
setvar $planetnames~planet_names[104] "Pagoda Outpost"
setvar $planetnames~planet_names[105] "Midgard"
setvar $planetnames~planet_names[106] "New Lutum"
setvar $planetnames~planet_names[107] "Curie Primus"
setvar $planetnames~planet_names[108] "New Kerogen"
setvar $planetnames~planet_names[109] "Brevico Outpost"
setvar $planetnames~planet_names[110] "Cleisthenes Annex"
setvar $planetnames~planet_names[111] "Banalg Primus"
setvar $planetnames~planet_names[112] "Hiruko Primus"
setvar $planetnames~planet_names[113] "New Canis Staz"
setvar $planetnames~planet_names[114] "Herschel Prime"
setvar $planetnames~planet_names[115] "Feesu Annex"
setvar $planetnames~planet_names[116] "Sluagh Minor"
setvar $planetnames~planet_names[117] "Acacia Primus"
setvar $planetnames~planet_names[118] "Zagreus Minor"
setvar $planetnames~planet_names[119] "Aud Outpost"
setvar $planetnames~planet_names[120] "Leo Annex"
setvar $planetnames~planet_names[121] "Inx Primus"
setvar $planetnames~planet_names[122] "Plugh Major"
setvar $planetnames~planet_names[123] "Keltcher II"
setvar $planetnames~planet_names[124] "El Nath Major"
setvar $planetnames~planet_names[125] "Thalim Outpost"
setvar $planetnames~planet_names[126] "Achilles Annex"
setvar $planetnames~planet_names[127] "New Janvier"
setvar $planetnames~planet_names[128] "New Mare"
setvar $planetnames~planet_names[129] "Osnabruck Minor"
setvar $planetnames~planet_names[130] "New Atropine"
setvar $planetnames~planet_names[131] "Hyksos Outpost"
setvar $planetnames~planet_names[132] "Ionicus Annex"
setvar $planetnames~planet_names[133] "Atwood Annex"
setvar $planetnames~planet_names[134] "Ektron II"
setvar $planetnames~planet_names[135] "New Debarre"
setvar $planetnames~planet_names[136] "New Hubble"
setvar $planetnames~planet_names[137] "Acridine Annex"
setvar $planetnames~planet_names[138] "Atchison Annex"
setvar $planetnames~planet_names[139] "Aeschylus Annex"
setvar $planetnames~planet_names[140] "Triceratops II"
setvar $planetnames~planet_names[141] "Ovid 962 Outpost"
setvar $planetnames~planet_names[142] "Laon Annex"
setvar $planetnames~planet_names[143] "Feesu II"
setvar $planetnames~planet_names[144] "Pysadi Outpost"
setvar $planetnames~planet_names[145] "Bansin II"
setvar $planetnames~planet_names[146] "Grimaldi Outpost"
setvar $planetnames~planet_names[147] "Kashyyyk Annex"
setvar $planetnames~planet_names[148] "New Pickering"
setvar $planetnames~planet_names[149] "Sardaukar"
setvar $planetnames~planet_names[150] "Poritrin Annex"
setvar $planetnames~planet_names[151] "Biela Minor"
setvar $planetnames~planet_names[152] "Autun Minor"
setvar $planetnames~planet_names[153] "Akira Primus"
setvar $planetnames~planet_names[154] "Bohemia III"
setvar $planetnames~planet_names[155] "Caspan Primus"
setvar $planetnames~planet_names[156] "Barite Minor"
setvar $planetnames~planet_names[157] "Loki Outpost"
setvar $planetnames~planet_names[158] "Argos Primus"
setvar $planetnames~planet_names[159] "Drake Annex"
setvar $planetnames~planet_names[160] "Jaspilate Outpost"
setvar $planetnames~planet_names[161] "New Tacaxeb"
setvar $planetnames~planet_names[162] "Brevico Primus"
setvar $planetnames~planet_names[163] "Bolivar Minor"
setvar $planetnames~planet_names[164] "Trennen Major"
setvar $planetnames~planet_names[165] "Bainite Annex"
setvar $planetnames~planet_names[166] "Amber Primus"
setvar $planetnames~planet_names[167] "Remorhaz"
setvar $planetnames~planet_names[168] "Politzer"
setvar $planetnames~planet_names[169] "Thisbe"
setvar $planetnames~planet_names[170] "Ekinus"
setvar $planetnames~planet_names[171] "Agamotto Annex"
setvar $planetnames~planet_names[172] "Ixzotz"
setvar $planetnames~planet_names[173] "Coliar"
setvar $planetnames~planet_names[174] "Dragon Major"
setvar $planetnames~planet_names[175] "Minimi Outpost"
setvar $planetnames~planet_names[176] "Comani II"
setvar $planetnames~planet_names[177] "Saladin Major"
setvar $planetnames~planet_names[178] "New CSM-101"
setvar $planetnames~planet_names[179] "Winston"
setvar $planetnames~planet_names[180] "Putman Outpost"
setvar $planetnames~planet_names[181] "Zarathrustra"
setvar $planetnames~planet_names[182] "Bacchus Outpost"
setvar $planetnames~planet_names[183] "Demantoid Annex"
setvar $planetnames~planet_names[184] "Aarite Outpost"
setvar $planetnames~planet_names[185] "Langres Primus"
setvar $planetnames~planet_names[186] "New Myk"
setvar $planetnames~planet_names[187] "Castalia Minor"
setvar $planetnames~planet_names[188] "Feyd Major"
setvar $planetnames~planet_names[189] "Gauss"
setvar $planetnames~planet_names[190] "Adurol Primus"
setvar $planetnames~planet_names[191] "Pingos Annex"
setvar $planetnames~planet_names[192] "Shih Hwang-ti Major"
setvar $planetnames~planet_names[193] "Homonculous Annex"
setvar $planetnames~planet_names[194] "Calandra Annex"
setvar $planetnames~planet_names[195] "Tartarus Minor"
setvar $planetnames~planet_names[196] "Njord Major"
setvar $planetnames~planet_names[197] "Melusine II"
setvar $planetnames~planet_names[198] "Cepheus"
setvar $planetnames~planet_names[199] "Huggins Primus"
setvar $planetnames~planet_names[200] "Buchanan"
setvar $planetnames~planet_names[201] "Bleigh Outpost"
setvar $planetnames~planet_names[202] "Abohm Annex"
setvar $planetnames~planet_names[203] "Freaque Primus"
setvar $planetnames~planet_names[204] "Bespin Outpost"
setvar $planetnames~planet_names[205] "Shklovsky"
setvar $planetnames~planet_names[206] "Heimdall Minor"
setvar $planetnames~planet_names[207] "New Bentylol"
setvar $planetnames~planet_names[208] "Lebeau"
setvar $planetnames~planet_names[209] "New Siva"
setvar $planetnames~planet_names[210] "Biggs Outpost"
setvar $planetnames~planet_names[211] "Auroran Major"
setvar $planetnames~planet_names[212] "Phoenix"
setvar $planetnames~planet_names[213] "Chaeta Major"
setvar $planetnames~planet_names[214] "Anacel Minor"
setvar $planetnames~planet_names[215] "Zeycude Minor"
setvar $planetnames~planet_names[216] "Akarso Major"
setvar $planetnames~planet_names[217] "Bifrost Primus"
setvar $planetnames~planet_names[218] "Jolotre Outpost"
setvar $planetnames~planet_names[219] "New Tutankhamen"
setvar $planetnames~planet_names[220] "Adams Outpost"
setvar $planetnames~planet_names[221] "Feynman Minor"
setvar $planetnames~planet_names[222] "Grant Primus"
setvar $planetnames~planet_names[223] "Aeon Primus"
setvar $planetnames~planet_names[224] "Sacajawea Minor"
setvar $planetnames~planet_names[225] "Thor Outpost"
setvar $planetnames~planet_names[226] "New Kashyyyk"
setvar $planetnames~planet_names[227] "Underwood Minor"
setvar $planetnames~planet_names[228] "Yukawa Major"
setvar $planetnames~planet_names[229] "Feesu Minor"
setvar $planetnames~planet_names[230] "Accurbron Major"
setvar $planetnames~planet_names[231] "Parthenon Major"
setvar $planetnames~planet_names[232] "Calan Outpost"
setvar $planetnames~planet_names[233] "Tali Annex"
setvar $planetnames~planet_names[234] "Cogri Outpost"
setvar $planetnames~planet_names[235] "Atwood Minor"
setvar $planetnames~planet_names[236] "Aldebaran"
setvar $planetnames~planet_names[237] "New Atreides"
setvar $planetnames~planet_names[238] "Abae Annex"
setvar $planetnames~planet_names[239] "Aurva Primus"
setvar $planetnames~planet_names[240] "Pogson Primus"
setvar $planetnames~planet_names[241] "Degtyarev Major"
setvar $planetnames~planet_names[242] "Wollaston"
setvar $planetnames~planet_names[243] "Eagle Annex"
setvar $planetnames~planet_names[244] "Atacon Annex"
setvar $planetnames~planet_names[245] "Lanth Major"
setvar $planetnames~planet_names[246] "Reber Primus"
setvar $planetnames~planet_names[247] "Aleph Minor"
setvar $planetnames~planet_names[248] "Dollond"
setvar $planetnames~planet_names[249] "H'Catha Minor"
setvar $planetnames~planet_names[250] "New Bacta"
setvar $planetnames~planet_names[251] "Galina Annex"
setvar $planetnames~planet_names[252] "New Nadrin"
setvar $planetnames~planet_names[253] "Ajacs Primus"
setvar $planetnames~planet_names[254] "Holland Annex"
setvar $planetnames~planet_names[255] "New Baraka"
setvar $planetnames~planet_names[256] "Alencika Minor"
setvar $planetnames~planet_names[257] "Wypoc"
setvar $planetnames~planet_names[258] "Mytus Major"
setvar $planetnames~planet_names[259] "Garuda Outpost"
setvar $planetnames~planet_names[260] "Nog Outpost"
setvar $planetnames~planet_names[261] "Arcturus Annex"
setvar $planetnames~planet_names[262] "El Cid II"
setvar $planetnames~planet_names[263] "Autun"
setvar $planetnames~planet_names[264] "Omega Major"
setvar $planetnames~planet_names[265] "Antike Outpost"
setvar $planetnames~planet_names[266] "Triceratops Primus"
setvar $planetnames~planet_names[267] "Caladan II"
setvar $planetnames~planet_names[268] "Gnosis II"
setvar $planetnames~planet_names[269] "Freedom"
setvar $planetnames~planet_names[270] "Solomon Primus"
setvar $planetnames~planet_names[271] "Flamarion Major"
setvar $planetnames~planet_names[272] "Massassi Minor"
setvar $planetnames~planet_names[273] "Baclofin Major"
setvar $planetnames~planet_names[274] "New Berubigen"
setvar $planetnames~planet_names[275] "Hydra"
setvar $planetnames~planet_names[276] "Ylaven Annex"
setvar $planetnames~planet_names[277] "Shcawbe"
setvar $planetnames~planet_names[278] "Dallia Primus"
setvar $planetnames~planet_names[279] "New FerNics"
setvar $planetnames~planet_names[280] "Cyzicus Outpost"
setvar $planetnames~planet_names[281] "Belenus"
setvar $planetnames~planet_names[282] "Kudu Minor"
setvar $planetnames~planet_names[283] "Shadout"
setvar $planetnames~planet_names[284] "Tetanus Major"
setvar $planetnames~planet_names[285] "Mecha Major"
setvar $planetnames~planet_names[286] "Blunderbuss Outpost"
setvar $planetnames~planet_names[287] "Castile"
setvar $planetnames~planet_names[288] "Dollond Annex"
setvar $planetnames~planet_names[289] "Condyole II"
setvar $planetnames~planet_names[290] "Benemid Outpost"
setvar $planetnames~planet_names[291] "New Kether"
setvar $planetnames~planet_names[292] "Scarabaeus"
setvar $planetnames~planet_names[293] "Spector Major"
setvar $planetnames~planet_names[294] "Nambu Annex"
setvar $planetnames~planet_names[295] "Yamoto II"
setvar $planetnames~planet_names[296] "Lockyer Major"
setvar $planetnames~planet_names[297] "New Huggins"
setvar $planetnames~planet_names[298] "Gorram"
setvar $planetnames~planet_names[299] "Minimi Minor"
setvar $planetnames~planet_names[300] "Sorel Major"
setvar $planetnames~planet_names[301] "El Nath Primus"
setvar $planetnames~planet_names[302] "Lumineaux Outpost"
setvar $planetnames~planet_names[303] "Richter Primus"
setvar $planetnames~planet_names[304] "Ilianeou"
setvar $planetnames~planet_names[305] "Xyvitix Annex"
setvar $planetnames~planet_names[306] "Benisone Minor"
setvar $planetnames~planet_names[307] "Fanning"
setvar $planetnames~planet_names[308] "Flamsteed"
setvar $planetnames~planet_names[309] "Shklovsky Primus"
setvar $planetnames~planet_names[310] "Toshi Annex"
setvar $planetnames~planet_names[311] "New Bumex"
setvar $planetnames~planet_names[312] "Noirmoutier"
setvar $planetnames~planet_names[313] "Macross"
setvar $planetnames~planet_names[314] "Du Fay Major"
setvar $planetnames~planet_names[315] "Ross Outpost"
setvar $planetnames~planet_names[316] "Xi Primus"
setvar $planetnames~planet_names[317] "Leyline II"
setvar $planetnames~planet_names[318] "Vergil Minor"
setvar $planetnames~planet_names[319] "Diocletian Outpost"
setvar $planetnames~planet_names[320] "Eisenhower Minor"
setvar $planetnames~planet_names[321] "Cithaeron Annex"
setvar $planetnames~planet_names[322] "Pockels Major"
setvar $planetnames~planet_names[323] "Rangent Major"
setvar $planetnames~planet_names[324] "Pascal Annex"
setvar $planetnames~planet_names[325] "Avitene Primus"
setvar $planetnames~planet_names[326] "Fantasia Primus"
setvar $planetnames~planet_names[327] "Baridium II"
setvar $planetnames~planet_names[328] "Von Zacjh II"
setvar $planetnames~planet_names[329] "Jasmine Annex"
setvar $planetnames~planet_names[330] "Bagasse II"
setvar $planetnames~planet_names[331] "Wern"
setvar $planetnames~planet_names[332] "Tenelphi Primus"
setvar $planetnames~planet_names[333] "Elmarin Major"
setvar $planetnames~planet_names[334] "New Rech"
setvar $planetnames~planet_names[335] "Massassi Major"
setvar $planetnames~planet_names[336] "Tintao"
setvar $planetnames~planet_names[337] "Engadine II"
setvar $planetnames~planet_names[338] "New Ektron"
setvar $planetnames~planet_names[339] "Ochecate"
setvar $planetnames~planet_names[340] "Peleus Minor"
setvar $planetnames~planet_names[341] "Balboa Minor"
setvar $planetnames~planet_names[342] "New Phobos"
setvar $planetnames~planet_names[343] "Elmarin II"
setvar $planetnames~planet_names[344] "Garion Primus"
setvar $planetnames~planet_names[345] "Sharrip Major"
setvar $planetnames~planet_names[346] "Breughel"
setvar $planetnames~planet_names[347] "Eisenhower II"
setvar $planetnames~planet_names[348] "Cusa II"
setvar $planetnames~planet_names[349] "Bralgu Annex"
setvar $planetnames~planet_names[350] "Copernicus II"
setvar $planetnames~planet_names[351] "Putman Annex"
setvar $planetnames~planet_names[352] "Pylus Minor"
setvar $planetnames~planet_names[353] "Alkaid"
setvar $planetnames~planet_names[354] "Proudelxak Primus"
setvar $planetnames~planet_names[355] "Putman II"
setvar $planetnames~planet_names[356] "Ganymede Major"
setvar $planetnames~planet_names[357] "Hotchkiss II"
setvar $planetnames~planet_names[358] "Eikonal Primus"
setvar $planetnames~planet_names[359] "New Nelson"
setvar $planetnames~planet_names[360] "Behemoth Annex"
setvar $planetnames~planet_names[361] "Daleth"
setvar $planetnames~planet_names[362] "Circe Primus"
setvar $planetnames~planet_names[363] "Ueilerm Annex"
setvar $planetnames~planet_names[364] "Winston Primus"
setvar $planetnames~planet_names[365] "Roentgen II"
setvar $planetnames~planet_names[366] "New Bentyl"
setvar $planetnames~planet_names[367] "Bainite Primus"
setvar $planetnames~planet_names[368] "Uranus Minor"
setvar $planetnames~planet_names[369] "Triumviri Outpost"
setvar $planetnames~planet_names[370] "Dearth Minor"
setvar $planetnames~planet_names[371] "Quare Minor"
setvar $planetnames~planet_names[372] "Ariel II"
setvar $planetnames~planet_names[373] "Agamotto"
setvar $planetnames~planet_names[374] "Mithras II"
setvar $planetnames~planet_names[375] "Agena II"
setvar $planetnames~planet_names[376] "Anchorhead Minor"
setvar $planetnames~planet_names[377] "Atarax Major"
setvar $planetnames~planet_names[378] "T'xe"
setvar $planetnames~planet_names[379] "Fedaykin Major"
setvar $planetnames~planet_names[380] "Kai Outpost"
setvar $planetnames~planet_names[381] "Pompey Major"
setvar $planetnames~planet_names[382] "Jarsone Major"
setvar $planetnames~planet_names[383] "Percy 1640 Major"
setvar $planetnames~planet_names[384] "Kraken Outpost"
setvar $planetnames~planet_names[385] "Tiree"
setvar $planetnames~planet_names[386] "New Corbiet"
setvar $planetnames~planet_names[387] "Celepina Minor"
setvar $planetnames~planet_names[388] "Augustus Annex"
setvar $planetnames~planet_names[389] "New H'Catha"
setvar $planetnames~planet_names[390] "New Aldrin"
setvar $planetnames~planet_names[391] "Bacarate II"
setvar $planetnames~planet_names[392] "Drude II"
setvar $planetnames~planet_names[393] "Millennium"
setvar $planetnames~planet_names[394] "Kwisatz"
setvar $planetnames~planet_names[395] "Rebka"
setvar $planetnames~planet_names[396] "Rebka II"
setvar $planetnames~planet_names[397] "Flamsteed Outpost"
setvar $planetnames~planet_names[398] "Garibaldi Minor"
setvar $planetnames~planet_names[399] "Hounstyr Annex"
setvar $planetnames~planet_names[400] "Flinte"
setvar $planetnames~planet_names[401] "Dodonna Major"
setvar $planetnames~planet_names[402] "Ueilerm Minor"
setvar $planetnames~planet_names[403] "Kaula"
setvar $planetnames~planet_names[404] "Orkney Outpost"
setvar $planetnames~planet_names[405] "Appollyon Primus"
setvar $planetnames~planet_names[406] "New Natoko"
setvar $planetnames~planet_names[407] "Heroni Major"
setvar $planetnames~planet_names[408] "Haderach Primus"
setvar $planetnames~planet_names[409] "Dinom Major"
setvar $planetnames~planet_names[410] "Darion Minor"
setvar $planetnames~planet_names[411] "Medusa II"
setvar $planetnames~planet_names[412] "Kaladan Outpost"
setvar $planetnames~planet_names[413] "Kep Salu Annex"
setvar $planetnames~planet_names[414] "New Minos"
setvar $planetnames~planet_names[415] "Jeeves Major"
setvar $planetnames~planet_names[416] "Exodus"
setvar $planetnames~planet_names[417] "Euler Annex"
setvar $planetnames~planet_names[418] "Capricornus II"
setvar $planetnames~planet_names[419] "Milan Primus"
setvar $planetnames~planet_names[420] "Beben Outpost"
setvar $planetnames~planet_names[421] "New Kohlrausch"
setvar $planetnames~planet_names[422] "Brombay"
setvar $planetnames~planet_names[423] "Alvarado Minor"
setvar $planetnames~planet_names[424] "New Franchi"
setvar $planetnames~planet_names[425] "Melior"
setvar $planetnames~planet_names[426] "Atrivis"
setvar $planetnames~planet_names[427] "Lepton II"
setvar $planetnames~planet_names[428] "Dyson Outpost"
setvar $planetnames~planet_names[429] "Feyd Outpost"
setvar $planetnames~planet_names[430] "Wypoc II"
setvar $planetnames~planet_names[431] "Peridot Primus"
setvar $planetnames~planet_names[432] "Yona II"
setvar $planetnames~planet_names[433] "Caduceus Major"
setvar $planetnames~planet_names[434] "Kruhious II"
setvar $planetnames~planet_names[435] "Melior Outpost"
setvar $planetnames~planet_names[436] "Ryloth Major"
setvar $planetnames~planet_names[437] "Becquerel Annex"
setvar $planetnames~planet_names[438] "Intrepid"
setvar $planetnames~planet_names[439] "Gascogne Annex"
setvar $planetnames~planet_names[440] "Free State II"
setvar $planetnames~planet_names[441] "Ozawa Minor"
setvar $planetnames~planet_names[442] "Mewey Primus"
setvar $planetnames~planet_names[443] "Xylene Outpost"
setvar $planetnames~planet_names[444] "Pohl Annex"
setvar $planetnames~planet_names[445] "Absarokite"
setvar $planetnames~planet_names[446] "Phardos Annex"
setvar $planetnames~planet_names[447] "Axolotl Minor"
setvar $planetnames~planet_names[448] "van der Waals Primus"
setvar $planetnames~planet_names[449] "Hydropon"
setvar $planetnames~planet_names[450] "Tesla Minor"
setvar $planetnames~planet_names[451] "Kender Annex"
setvar $planetnames~planet_names[452] "Aphrodite Primus"
setvar $planetnames~planet_names[453] "New Addax"
setvar $planetnames~planet_names[454] "New Castile"
setvar $planetnames~planet_names[455] "Atlas Major"
setvar $planetnames~planet_names[456] "Van de Graaff II"
setvar $planetnames~planet_names[457] "Chrysa II"
setvar $planetnames~planet_names[458] "Dirac Outpost"
setvar $planetnames~planet_names[459] "Aachen Annex"
setvar $planetnames~planet_names[460] "Skinfaxi II"
setvar $planetnames~planet_names[461] "Carthage Primus"
setvar $planetnames~planet_names[462] "Elmarin Outpost"
setvar $planetnames~planet_names[463] "Mikado Primus"
setvar $planetnames~planet_names[464] "Rydberg Minor"
setvar $planetnames~planet_names[465] "Hallwachs Major"
setvar $planetnames~planet_names[466] "Banderlog Major"
setvar $planetnames~planet_names[467] "New Grosseteste"
setvar $planetnames~planet_names[468] "Caliver II"
setvar $planetnames~planet_names[469] "Jokwa Primus"
setvar $planetnames~planet_names[470] "New Auxerre"
setvar $planetnames~planet_names[471] "Demilich"
setvar $planetnames~planet_names[472] "New Karelia"
setvar $planetnames~planet_names[473] "Rueschhoff"
setvar $planetnames~planet_names[474] "Taro Minor"
setvar $planetnames~planet_names[475] "Dianoga Annex"
setvar $planetnames~planet_names[476] "Quevedo Major"
setvar $planetnames~planet_names[477] "New Leviathan"
setvar $planetnames~planet_names[478] "Raydrad Primus"
setvar $planetnames~planet_names[479] "New Daleth"
setvar $planetnames~planet_names[480] "Metztla'Xym"
setvar $planetnames~planet_names[481] "Aix-la-Chapelle Annex"
setvar $planetnames~planet_names[482] "Spume Outpost"
setvar $planetnames~planet_names[483] "Lysander II"
setvar $planetnames~planet_names[484] "Simorg Minor"
setvar $planetnames~planet_names[485] "Van Maanen Outpost"
setvar $planetnames~planet_names[486] "Alexander II"
setvar $planetnames~planet_names[487] "Istar Annex"
setvar $planetnames~planet_names[488] "Crecy Major"
setvar $planetnames~planet_names[489] "Bethune Outpost"
setvar $planetnames~planet_names[490] "Cittert Major"
setvar $planetnames~planet_names[491] "Edinina II"
setvar $planetnames~planet_names[492] "Imbrium"
setvar $planetnames~planet_names[493] "New Tycho"
setvar $planetnames~planet_names[494] "Nordenfelt Annex"
setvar $planetnames~planet_names[495] "Dixon Primus"
setvar $planetnames~planet_names[496] "Biggs Major"
setvar $planetnames~planet_names[497] "Far Station II"
setvar $planetnames~planet_names[498] "Puparkin II"
setvar $planetnames~planet_names[499] "New Duras"
setvar $planetnames~planet_names[500] "Freedom II"
setvar $planetnames~planet_names[501] "Ardonyx Major"
setvar $planetnames~planet_names[502] "Focaline Major"
setvar $planetnames~planet_names[503] "Jacent II"
setvar $planetnames~planet_names[504] "Jimson Primus"
setvar $planetnames~planet_names[505] "Andromeda Primus"
setvar $planetnames~planet_names[506] "Adenine Outpost"
setvar $planetnames~planet_names[507] "Ampere Major"
setvar $planetnames~planet_names[508] "Cordoba Major"
setvar $planetnames~planet_names[509] "Garion Major"
setvar $planetnames~planet_names[510] "Gormenghast Primus"
setvar $planetnames~planet_names[511] "Roxana II"
setvar $planetnames~planet_names[512] "New Duriron"
setvar $planetnames~planet_names[513] "Islip Annex"
setvar $planetnames~planet_names[514] "New Powaza"
setvar $planetnames~planet_names[515] "Thisbe II"
setvar $planetnames~planet_names[516] "Ney Annex"
setvar $planetnames~planet_names[517] "Phlogiston Annex"
setvar $planetnames~planet_names[518] "Ganymede II"
setvar $planetnames~planet_names[519] "Joshi Major"
setvar $planetnames~planet_names[520] "Hajj Annex"
setvar $planetnames~planet_names[521] "Aceta Major"
setvar $planetnames~planet_names[522] "Idris II"
setvar $planetnames~planet_names[523] "New Gelugon"
setvar $planetnames~planet_names[524] "Shai-Hulud II"
setvar $planetnames~planet_names[525] "Towers Major"
setvar $planetnames~planet_names[526] "Tulan Primus"
setvar $planetnames~planet_names[527] "Massassi Primus"
setvar $planetnames~planet_names[528] "Taaug Annex"
setvar $planetnames~planet_names[529] "Baruch Outpost"
setvar $planetnames~planet_names[530] "Castalia"
setvar $planetnames~planet_names[531] "Penkwhar Outpost"
setvar $planetnames~planet_names[532] "Baugi Outpost"
setvar $planetnames~planet_names[533] "Draconis Outpost"
setvar $planetnames~planet_names[534] "Crimson II"
setvar $planetnames~planet_names[535] "Smoug Major"
setvar $planetnames~planet_names[536] "Asmussen Primus"
setvar $planetnames~planet_names[537] "Oort"
setvar $planetnames~planet_names[538] "Rousseau Major"
setvar $planetnames~planet_names[539] "Lahara Outpost"
setvar $planetnames~planet_names[540] "Belemmite Primus"
setvar $planetnames~planet_names[541] "Mainz Outpost"
setvar $planetnames~planet_names[542] "Corbino Outpost"
setvar $planetnames~planet_names[543] "Tanar'ri Major"
setvar $planetnames~planet_names[544] "Conway"
setvar $planetnames~planet_names[545] "Raweh II"
setvar $planetnames~planet_names[546] "New Hefry"
setvar $planetnames~planet_names[547] "Pinus Nigra Annex"
setvar $planetnames~planet_names[548] "Celepina Primus"
setvar $planetnames~planet_names[549] "Zaire Outpost"
setvar $planetnames~planet_names[550] "Medusa Annex"
setvar $planetnames~planet_names[551] "Tyrfing Outpost"
setvar $planetnames~planet_names[552] "Gormenghast Minor"
setvar $planetnames~planet_names[553] "Iliopoulos Annex"
setvar $planetnames~planet_names[554] "New Sacha"
setvar $planetnames~planet_names[555] "Tulan Outpost"
setvar $planetnames~planet_names[556] "Chaucer Primus"
setvar $planetnames~planet_names[557] "Carbonara Major"
setvar $planetnames~planet_names[558] "Zivije Minor"
setvar $planetnames~planet_names[559] "New Grant"
setvar $planetnames~planet_names[560] "Hadron Annex"
setvar $planetnames~planet_names[561] "New Chattur"
setvar $planetnames~planet_names[562] "Simeon Outpost"
setvar $planetnames~planet_names[563] "Moriarity Major"
setvar $planetnames~planet_names[564] "Heisenberg Outpost"
setvar $planetnames~planet_names[565] "Vingolf Major"
setvar $planetnames~planet_names[566] "Mammon Outpost"
setvar $planetnames~planet_names[567] "Ceres Outpost"
setvar $planetnames~planet_names[568] "Mantene"
setvar $planetnames~planet_names[569] "Capon Annex"
setvar $planetnames~planet_names[570] "Pockels Outpost"
setvar $planetnames~planet_names[571] "New Valiant"
setvar $planetnames~planet_names[572] "Buchanan II"
setvar $planetnames~planet_names[573] "Bevey Minor"
setvar $planetnames~planet_names[574] "New DarGer"
setvar $planetnames~planet_names[575] "Tatooine Primus"
setvar $planetnames~planet_names[576] "Rabwhar Primus"
setvar $planetnames~planet_names[577] "Trin Minor"
setvar $planetnames~planet_names[578] "Tyr Annex"
setvar $planetnames~planet_names[579] "Klystron"
setvar $planetnames~planet_names[580] "Zamine"
setvar $planetnames~planet_names[581] "Canis Staz II"
setvar $planetnames~planet_names[582] "Gungnir Minor"
setvar $planetnames~planet_names[583] "Alupent Major"
setvar $planetnames~planet_names[584] "Gideon Minor"
setvar $planetnames~planet_names[585] "Raweh Annex"
setvar $planetnames~planet_names[586] "Kamerlingh Annex"
setvar $planetnames~planet_names[587] "Camazotz Minor"
setvar $planetnames~planet_names[588] "Aeolus II"
setvar $planetnames~planet_names[589] "Grant Annex"
setvar $planetnames~planet_names[590] "Betelgeuse"
setvar $planetnames~planet_names[591] "New Dammar"
setvar $planetnames~planet_names[592] "Ursula"
setvar $planetnames~planet_names[593] "Fermi Minor"
setvar $planetnames~planet_names[594] "New Mewey"
setvar $planetnames~planet_names[595] "Elixabeth Outpost"
setvar $planetnames~planet_names[596] "Glashow II"
setvar $planetnames~planet_names[597] "Inchin"
setvar $planetnames~planet_names[598] "Antike"
setvar $planetnames~planet_names[599] "Iliopoulos Primus"
setvar $planetnames~planet_names[600] "Sigma Annex"
setvar $planetnames~planet_names[601] "Tetanus II"
setvar $planetnames~planet_names[602] "New Laika"
setvar $planetnames~planet_names[603] "Lorentz"
setvar $planetnames~planet_names[604] "Hefry"
setvar $planetnames~planet_names[605] "Smoug Annex"
setvar $planetnames~planet_names[606] "New Rutledge"
setvar $planetnames~planet_names[607] "Knossos"
setvar $planetnames~planet_names[608] "Cyclone II"
setvar $planetnames~planet_names[609] "New Milan"
setvar $planetnames~planet_names[610] "Mammon Major"
setvar $planetnames~planet_names[611] "Indium II"
setvar $planetnames~planet_names[612] "Tleilaxu Annex"
setvar $planetnames~planet_names[613] "Krosec II"
setvar $planetnames~planet_names[614] "New Surplus"
setvar $planetnames~planet_names[615] "Aerolone Primus"
setvar $planetnames~planet_names[616] "Nerewhon Outpost"
setvar $planetnames~planet_names[617] "Trexalon Primus"
setvar $planetnames~planet_names[618] "Spider Primus"
setvar $planetnames~planet_names[619] "Ontalak"
setvar $planetnames~planet_names[620] "Benemid Minor"
setvar $planetnames~planet_names[621] "Belenus Primus"
setvar $planetnames~planet_names[622] "Bismarck"
setvar $planetnames~planet_names[623] "New Carson"
setvar $planetnames~planet_names[624] "Rayl Major"
setvar $planetnames~planet_names[625] "New Fedaykin"
setvar $planetnames~planet_names[626] "Ent II"
setvar $planetnames~planet_names[627] "Cetacean II"
setvar $planetnames~planet_names[628] "Artemis"
setvar $planetnames~planet_names[629] "Shakespeare Major"
setvar $planetnames~planet_names[630] "Pepin Minor"
setvar $planetnames~planet_names[631] "Priedo Annex"
setvar $planetnames~planet_names[632] "Ryloth Annex"
setvar $planetnames~planet_names[633] "Pangelinan Annex"
setvar $planetnames~planet_names[634] "Arels II"
setvar $planetnames~planet_names[635] "Epsilon Major"
setvar $planetnames~planet_names[636] "Bayer Primus"
setvar $planetnames~planet_names[637] "Kruger Outpost"
setvar $planetnames~planet_names[638] "Chandrasekher Outpost"
setvar $planetnames~planet_names[639] "Imbrium Major"
setvar $planetnames~planet_names[640] "New Jolotre"
setvar $planetnames~planet_names[641] "Dearth II"
setvar $planetnames~planet_names[642] "New Hallwachs"
setvar $planetnames~planet_names[643] "Hounstyr II"
setvar $planetnames~planet_names[644] "Niepce Primus"
setvar $planetnames~planet_names[645] "Minddagger's Throne"
setvar $planetnames~planet_names[646] "Carnot Outpost"
setvar $planetnames~planet_names[647] "Diancecht Outpost"
setvar $planetnames~planet_names[648] "Gormenghast Annex"
setvar $planetnames~planet_names[649] "Adansonia Primus"
setvar $planetnames~planet_names[650] "Tolchock Primus"
setvar $planetnames~planet_names[651] "Cordwainer"
setvar $planetnames~planet_names[652] "Rahman Primus"
setvar $planetnames~planet_names[653] "Amicar Outpost"
setvar $planetnames~planet_names[654] "Galahad II"
setvar $planetnames~planet_names[655] "New Khancuhn"
setvar $planetnames~planet_names[656] "Glyth Major"
setvar $planetnames~planet_names[657] "Dolldus Major"
setvar $planetnames~planet_names[658] "Reigar Outpost"
setvar $planetnames~planet_names[659] "Aristophanes"
setvar $planetnames~planet_names[660] "Foelen"
setvar $planetnames~planet_names[661] "Gagarin Annex"
setvar $planetnames~planet_names[662] "Yucca"
setvar $planetnames~planet_names[663] "Earwig"
setvar $planetnames~planet_names[664] "Ithaca Primus"
setvar $planetnames~planet_names[665] "El Cid Annex"
setvar $planetnames~planet_names[666] "Geronimo Outpost"
setvar $planetnames~planet_names[667] "Couatl Minor"
setvar $planetnames~planet_names[668] "New Kahn"
setvar $planetnames~planet_names[669] "New Acetylene"
setvar $planetnames~planet_names[670] "Nebuchadnezzar Annex"
setvar $planetnames~planet_names[671] "Jimson Minor"
setvar $planetnames~planet_names[672] "Iota Outpost"
setvar $planetnames~planet_names[673] "Carse II"
setvar $planetnames~planet_names[674] "Opus Outpost"
setvar $planetnames~planet_names[675] "Smekal"
setvar $planetnames~planet_names[676] "Ypsilon Primus"
setvar $planetnames~planet_names[677] "New Auralgan"
setvar $planetnames~planet_names[678] "Nin'arth Minor"
setvar $planetnames~planet_names[679] "Hohenstaufen II"
setvar $planetnames~planet_names[680] "Hefry Major"
setvar $planetnames~planet_names[681] "Faust Outpost"
setvar $planetnames~planet_names[682] "New Hagal"
setvar $planetnames~planet_names[683] "IronWollobick Annex"
setvar $planetnames~planet_names[684] "Sisko Minor"
setvar $planetnames~planet_names[685] "Piazzi Minor"
setvar $planetnames~planet_names[686] "Mirazh II"
setvar $planetnames~planet_names[687] "Myk Outpost"
setvar $planetnames~planet_names[688] "Bumex Minor"
setvar $planetnames~planet_names[689] "Feyd II"
setvar $planetnames~planet_names[690] "Hadron Major"
setvar $planetnames~planet_names[691] "Cyberdyne Outpost"
setvar $planetnames~planet_names[692] "D'Alembert Primus"
setvar $planetnames~planet_names[693] "Brigantia Annex"
setvar $planetnames~planet_names[694] "Miaplacidas Primus"
setvar $planetnames~planet_names[695] "Schwarzlose Annex"
setvar $planetnames~planet_names[696] "Datolite Annex"
setvar $planetnames~planet_names[697] "Gormenghast Outpost"
setvar $planetnames~planet_names[698] "Ithaca II"
setvar $planetnames~planet_names[699] "Condaria Primus"
setvar $planetnames~planet_names[700] "Draconis"
setvar $planetnames~planet_names[701] "Praxis"
setvar $planetnames~planet_names[702] "Brodie Primus"
setvar $planetnames~planet_names[703] "Katana Outpost"
setvar $planetnames~planet_names[704] "New Zoptica"
setvar $planetnames~planet_names[705] "New Bonta"
setvar $planetnames~planet_names[706] "Deschuner Primus"
setvar $planetnames~planet_names[707] "Hecate II"
setvar $planetnames~planet_names[708] "Siembieda Primus"
setvar $planetnames~planet_names[709] "Edinina Annex"
setvar $planetnames~planet_names[710] "Saxe Outpost"
setvar $planetnames~planet_names[711] "Fractine Annex"
setvar $planetnames~planet_names[712] "Schrodinger Primus"
setvar $planetnames~planet_names[713] "Gautier"
setvar $planetnames~planet_names[714] "Akkad Outpost"
setvar $planetnames~planet_names[715] "Polk Minor"
setvar $planetnames~planet_names[716] "New Brae Taera"
setvar $planetnames~planet_names[717] "DeGleash Outpost"
setvar $planetnames~planet_names[718] "Breon Annex"
setvar $planetnames~planet_names[719] "Adjutant"
setvar $planetnames~planet_names[720] "Bridger"
setvar $planetnames~planet_names[721] "New Dinomn"
setvar $planetnames~planet_names[722] "Sinmora"
setvar $planetnames~planet_names[723] "Wein Major"
setvar $planetnames~planet_names[724] "Skuld Major"
setvar $planetnames~planet_names[725] "Tau Major"
setvar $planetnames~planet_names[726] "Eocene Primus"
setvar $planetnames~planet_names[727] "Russel"
setvar $planetnames~planet_names[728] "Samson"
setvar $planetnames~planet_names[729] "Ponsby Primus"
setvar $planetnames~planet_names[730] "Koenig Minor"
setvar $planetnames~planet_names[731] "Constellate"
setvar $planetnames~planet_names[732] "New Verdun"
setvar $planetnames~planet_names[733] "New Heroni"
setvar $planetnames~planet_names[734] "New Dopp"
setvar $planetnames~planet_names[735] "Adhara Primus"
setvar $planetnames~planet_names[736] "Van Maanen II"
setvar $planetnames~planet_names[737] "Prokhorov II"
setvar $planetnames~planet_names[738] "Fabrina II"
setvar $planetnames~planet_names[739] "Ambartsumian Major"
setvar $planetnames~planet_names[740] "New Toro"
setvar $planetnames~planet_names[741] "New Sirius"
setvar $planetnames~planet_names[742] "Poisson II"
setvar $planetnames~planet_names[743] "New Deris"
setvar $planetnames~planet_names[744] "Nadrin Primus"
setvar $planetnames~planet_names[745] "Riyal Primus"
setvar $planetnames~planet_names[746] "New Hippocrates"
setvar $planetnames~planet_names[747] "Bainite Major"
setvar $planetnames~planet_names[748] "Hertz Annex"
setvar $planetnames~planet_names[749] "Athach"
setvar $planetnames~planet_names[750] "Torment Primus"
setvar $planetnames~planet_names[751] "Bohr Outpost"
setvar $planetnames~planet_names[752] "Copalite Outpost"
setvar $planetnames~planet_names[753] "Vero"
setvar $planetnames~planet_names[754] "Alfa Primus"
setvar $planetnames~planet_names[755] "Wolf II"
setvar $planetnames~planet_names[756] "Banalg"
setvar $planetnames~planet_names[757] "Lepton"
setvar $planetnames~planet_names[758] "Bardeleben II"
setvar $planetnames~planet_names[759] "Boyle Minor"
setvar $planetnames~planet_names[760] "Aston Annex"
setvar $planetnames~planet_names[761] "Proxima Centauri Major"
setvar $planetnames~planet_names[762] "Bielids Primus"
setvar $planetnames~planet_names[763] "Amber Major"
setvar $planetnames~planet_names[764] "Gorgimera II"
setvar $planetnames~planet_names[765] "Mortai Minor"
setvar $planetnames~planet_names[766] "Hecate Primus"
setvar $planetnames~planet_names[767] "Sabine"
setvar $planetnames~planet_names[768] "Kintaro Annex"
setvar $planetnames~planet_names[769] "Knorbes"
setvar $planetnames~planet_names[770] "Sirion Primus"
setvar $planetnames~planet_names[771] "New Priedo"
setvar $planetnames~planet_names[772] "Deris"
setvar $planetnames~planet_names[773] "Sakai II"
setvar $planetnames~planet_names[774] "Jefferson II"
setvar $planetnames~planet_names[775] "Flinte Minor"
setvar $planetnames~planet_names[776] "New Gaillot"
setvar $planetnames~planet_names[777] "New Ozawa"
setvar $planetnames~planet_names[778] "Valkyrie Major"
setvar $planetnames~planet_names[779] "Helios Primus"
setvar $planetnames~planet_names[780] "Castor Annex"
setvar $planetnames~planet_names[781] "Lysander Outpost"
setvar $planetnames~planet_names[782] "Engrange Major"
setvar $planetnames~planet_names[783] "Hektor Outpost"
setvar $planetnames~planet_names[784] "Quasi Primus"
setvar $planetnames~planet_names[785] "Minimi Annex"
setvar $planetnames~planet_names[786] "Cetacean Primus"
setvar $planetnames~planet_names[787] "Mondoloy"
setvar $planetnames~planet_names[788] "Hadozee II"
setvar $planetnames~planet_names[789] "Giedi Staz Primus"
setvar $planetnames~planet_names[790] "Sarnoff Primus"
setvar $planetnames~planet_names[791] "Symbiont Annex"
setvar $planetnames~planet_names[792] "New Atrivis"
setvar $planetnames~planet_names[793] "Adurol Outpost"
setvar $planetnames~planet_names[794] "Agamar Minor"
setvar $planetnames~planet_names[795] "de Tocqueville II"
setvar $planetnames~planet_names[796] "Kentaurus"
setvar $planetnames~planet_names[797] "Nebecula"
setvar $planetnames~planet_names[798] "Mach Primus"
setvar $planetnames~planet_names[799] "New Marconi"
setvar $planetnames~planet_names[800] "Pixie Outpost"
setvar $planetnames~planet_names[801] "Scorpio II"
setvar $planetnames~planet_names[802] "Greyhawk Outpost"
setvar $planetnames~planet_names[803] "New Bernoulli"
setvar $planetnames~planet_names[804] "Myk"
setvar $planetnames~planet_names[805] "New Snell"
setvar $planetnames~planet_names[806] "Buccal II"
setvar $planetnames~planet_names[807] "Surplus Outpost"
setvar $planetnames~planet_names[808] "Agathinon"
setvar $planetnames~planet_names[809] "Esabl Major"
setvar $planetnames~planet_names[810] "l'Hopital Primus"
setvar $planetnames~planet_names[811] "New Farquahar"
setvar $planetnames~planet_names[812] "Calit Annex"
setvar $planetnames~planet_names[813] "Forni-Copus Primus"
setvar $planetnames~planet_names[814] "Dreath Annex"
setvar $planetnames~planet_names[815] "Messier II"
setvar $planetnames~planet_names[816] "New Bethune"
setvar $planetnames~planet_names[817] "Avauld Major"
setvar $planetnames~planet_names[818] "New Brassica"
setvar $planetnames~planet_names[819] "Scheiner Minor"
setvar $planetnames~planet_names[820] "Focaline II"
setvar $planetnames~planet_names[821] "Xructocex Minor"
setvar $planetnames~planet_names[822] "Atozine II"
setvar $planetnames~planet_names[823] "Alupent Annex"
setvar $planetnames~planet_names[824] "Moran II"
setvar $planetnames~planet_names[825] "Bularia II"
setvar $planetnames~planet_names[826] "Natoko Major"
setvar $planetnames~planet_names[827] "Jenghe"
setvar $planetnames~planet_names[828] "Thanber II"
setvar $planetnames~planet_names[829] "Aeacus Major"
setvar $planetnames~planet_names[830] "New Avignon"
setvar $planetnames~planet_names[831] "Annobon Primus"
setvar $planetnames~planet_names[832] "Majorana"
setvar $planetnames~planet_names[833] "Alarm Major"
setvar $planetnames~planet_names[834] "Messier"
setvar $planetnames~planet_names[835] "Steele Minor"
setvar $planetnames~planet_names[836] "Njord II"
setvar $planetnames~planet_names[837] "Diabase Primus"
setvar $planetnames~planet_names[838] "Pagaton Minor"
setvar $planetnames~planet_names[839] "Aston Major"
setvar $planetnames~planet_names[840] "Rashomon Outpost"
setvar $planetnames~planet_names[841] "Yiktor"
setvar $planetnames~planet_names[842] "Azactam II"
setvar $planetnames~planet_names[843] "Anastasya II"
setvar $planetnames~planet_names[844] "Cogri"
setvar $planetnames~planet_names[845] "Macross Minor"
setvar $planetnames~planet_names[846] "Asteres Major"
setvar $planetnames~planet_names[847] "Bernoulli II"
setvar $planetnames~planet_names[848] "New Pagoda"
setvar $planetnames~planet_names[849] "Einherjar Primus"
setvar $planetnames~planet_names[850] "Palpatine"
setvar $planetnames~planet_names[851] "New Ghanima"
setvar $planetnames~planet_names[852] "Poitiers II"
setvar $planetnames~planet_names[853] "Nautiloid II"
setvar $planetnames~planet_names[854] "Zoptica Minor"
setvar $planetnames~planet_names[855] "Wern II"
setvar $planetnames~planet_names[856] "Cascara Annex"
setvar $planetnames~planet_names[857] "Yurst Outpost"
setvar $planetnames~planet_names[858] "Breughel Major"
setvar $planetnames~planet_names[859] "Anchorhead Outpost"
setvar $planetnames~planet_names[860] "Woden Annex"
setvar $planetnames~planet_names[861] "Gaia"
setvar $planetnames~planet_names[862] "New Orwell"
setvar $planetnames~planet_names[863] "Diocletian Primus"
setvar $planetnames~planet_names[864] "New Exedore"
setvar $planetnames~planet_names[865] "Jupura Major"
setvar $planetnames~planet_names[866] "Kerogen"
setvar $planetnames~planet_names[867] "Krono Major"
setvar $planetnames~planet_names[868] "Marmoutier Major"
setvar $planetnames~planet_names[869] "Stokes Annex"
setvar $planetnames~planet_names[870] "New Pluto"
setvar $planetnames~planet_names[871] "Hornet II"
setvar $planetnames~planet_names[872] "Telegraph Major"
setvar $planetnames~planet_names[873] "Bolivar Outpost"
setvar $planetnames~planet_names[874] "Iolcus II"
setvar $planetnames~planet_names[875] "Noegi Major"
setvar $planetnames~planet_names[876] "New Saladin"
setvar $planetnames~planet_names[877] "Cambridge Annex"
setvar $planetnames~planet_names[878] "Gelugon"
setvar $planetnames~planet_names[879] "Lazarus II"
setvar $planetnames~planet_names[880] "Achernar Primus"
setvar $planetnames~planet_names[881] "Langmuir"
setvar $planetnames~planet_names[882] "Buie Annex"
setvar $planetnames~planet_names[883] "Spica"
setvar $planetnames~planet_names[884] "Puparkin Outpost"
setvar $planetnames~planet_names[885] "Maya Major"
setvar $planetnames~planet_names[886] "New Polk"
setvar $planetnames~planet_names[887] "Solon Minor"
setvar $planetnames~planet_names[888] "Flamarion Primus"
setvar $planetnames~planet_names[889] "Jupura Minor"
setvar $planetnames~planet_names[890] "New Lahara"
setvar $planetnames~planet_names[891] "New Hermes"
setvar $planetnames~planet_names[892] "New Krono"
setvar $planetnames~planet_names[893] "Starling Primus"
setvar $planetnames~planet_names[894] "Vanant"
setvar $planetnames~planet_names[895] "New Rebka"
setvar $planetnames~planet_names[896] "Julian Major"
setvar $planetnames~planet_names[897] "Faeroes"
setvar $planetnames~planet_names[898] "Kongo"
setvar $planetnames~planet_names[899] "Lorraine Annex"
setvar $planetnames~planet_names[900] "Gautier Outpost"
setvar $planetnames~planet_names[901] "New Hadar"
setvar $planetnames~planet_names[902] "Nexine II"
setvar $planetnames~planet_names[903] "Lindbergh Annex"
setvar $planetnames~planet_names[904] "Ranger"
setvar $planetnames~planet_names[905] "Strad Primus"
setvar $planetnames~planet_names[906] "Yuro Minor"
setvar $planetnames~planet_names[907] "New Ilium"
setvar $planetnames~planet_names[908] "Peale"
setvar $planetnames~planet_names[909] "Faisal Primus"
setvar $planetnames~planet_names[910] "Skinfaxi Major"
setvar $planetnames~planet_names[911] "Gaea Primus"
setvar $planetnames~planet_names[912] "Ayat Major"
setvar $planetnames~planet_names[913] "Charlemagne Minor"
setvar $planetnames~planet_names[914] "Dixon II"
setvar $planetnames~planet_names[915] "Pequan Annex"
setvar $planetnames~planet_names[916] "Arden Annex"
setvar $planetnames~planet_names[917] "Palitzsch II"
setvar $planetnames~planet_names[918] "Seneca Annex"
setvar $planetnames~planet_names[919] "Bozarth Annex"
setvar $planetnames~planet_names[920] "Bicornn Outpost"
setvar $planetnames~planet_names[921] "Djinn Primus"
setvar $planetnames~planet_names[922] "Nabopolassar II"
setvar $planetnames~planet_names[923] "Adhara Major"
setvar $planetnames~planet_names[924] "New Nagant"
setvar $planetnames~planet_names[925] "Julian"
setvar $planetnames~planet_names[926] "Upatnieks Annex"
setvar $planetnames~planet_names[927] "New Guatama"
setvar $planetnames~planet_names[928] "Isolux Outpost"
setvar $planetnames~planet_names[929] "Archon Annex"
setvar $planetnames~planet_names[930] "Planitia Major"
setvar $planetnames~planet_names[931] "Li Kao Minor"
setvar $planetnames~planet_names[932] "Cogri Minor"
setvar $planetnames~planet_names[933] "New Shcawbe"
setvar $planetnames~planet_names[934] "Kruhious Outpost"
setvar $planetnames~planet_names[935] "Castor Hideout"
setvar $planetnames~planet_names[936] "Clastic Outpost"
setvar $planetnames~planet_names[937] "New Capybara"
setvar $planetnames~planet_names[938] "Durer"
setvar $planetnames~planet_names[939] "New Durendal"
setvar $planetnames~planet_names[940] "Tivid"
setvar $planetnames~planet_names[941] "New Vreibefger"
setvar $planetnames~planet_names[942] "Baugi Major"
setvar $planetnames~planet_names[943] "Lorraine Minor"
setvar $planetnames~planet_names[944] "Chalcedony Major"
setvar $planetnames~planet_names[945] "Rousseau Annex"
setvar $planetnames~planet_names[946] "Palique Outpost"
setvar $planetnames~planet_names[947] "Valence Annex"
setvar $planetnames~planet_names[948] "Ralhe Minor"
setvar $planetnames~planet_names[949] "Kruxas Ruz Annex"
setvar $planetnames~planet_names[950] "Pyris Primus"
setvar $planetnames~planet_names[951] "New Earwig"
setvar $planetnames~planet_names[952] "New Wintjen"
setvar $planetnames~planet_names[953] "Pennington"
setvar $planetnames~planet_names[954] "Koalinth"
setvar $planetnames~planet_names[955] "Antike Annex"
setvar $planetnames~planet_names[956] "Bach Major"
setvar $planetnames~planet_names[957] "Kikusui"
setvar $planetnames~planet_names[958] "Guatama Minor"
setvar $planetnames~planet_names[959] "Gaderffii"
setvar $planetnames~planet_names[960] "Kender"
setvar $planetnames~planet_names[961] "Mithra Minor"
setvar $planetnames~planet_names[962] "Osnabruck Primus"
setvar $planetnames~planet_names[963] "Pedase II"
setvar $planetnames~planet_names[964] "Murchison Primus"
setvar $planetnames~planet_names[965] "Lafaayette Outpost"
setvar $planetnames~planet_names[966] "Dawnworld"
setvar $planetnames~planet_names[967] "Ajacs"
setvar $planetnames~planet_names[968] "Raven Outpost"
setvar $planetnames~planet_names[969] "Bravera II"
setvar $planetnames~planet_names[970] "Edenelt Primus"
setvar $planetnames~planet_names[971] "New Nicholson"
setvar $planetnames~planet_names[972] "Suleiman Outpost"
setvar $planetnames~planet_names[973] "Alva"
setvar $planetnames~planet_names[974] "Amertet Annex"
setvar $planetnames~planet_names[975] "Guellan Minor"
setvar $planetnames~planet_names[976] "Thagar"
setvar $planetnames~planet_names[977] "Kegena"
setvar $planetnames~planet_names[978] "Ari Outpost"
setvar $planetnames~planet_names[979] "Hawk Primus"
setvar $planetnames~planet_names[980] "Abraxas Minor"
setvar $planetnames~planet_names[981] "Columbus"
setvar $planetnames~planet_names[982] "Rutledge Major"
setvar $planetnames~planet_names[983] "Efate Major"
setvar $planetnames~planet_names[984] "Xylem Primus"
setvar $planetnames~planet_names[985] "Anaspaz Major"
setvar $planetnames~planet_names[986] "Garoo Minor"
setvar $planetnames~planet_names[987] "Kruhious Minor"
setvar $planetnames~planet_names[988] "Camelot Major"
setvar $planetnames~planet_names[989] "Singer Minor"
setvar $planetnames~planet_names[990] "Aegospotami Primus"
setvar $planetnames~planet_names[991] "Modelei Annex"
setvar $planetnames~planet_names[992] "Skuld Outpost"
setvar $planetnames~planet_names[993] "Oisin Outpost"
setvar $planetnames~planet_names[994] "Baruch Major"
setvar $planetnames~planet_names[995] "Pyramus II"
setvar $planetnames~planet_names[996] "Thornastor Outpost"
setvar $planetnames~planet_names[997] "Suleiman"
setvar $planetnames~planet_names[998] "Pompey Primus"
setvar $planetnames~planet_names[999] "New Aeschylus"
setvar $planetnames~planet_names[1000] "Bounty's Horizon"
return
